(()=>{let sock=null,selfId=null,isSpy=false,latest=null,guessMode=false;
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function roomCode(){return ($('gameRoomCode')?.textContent||$('roomCodeLabel')?.textContent||'').trim()}
function playerName(){return ($('playerName')?.value||window.spyfallSelfName||'').trim()}
function ensureActionButtons(){const side=document.querySelector('.side-actions');if(!side)return;let card=$('actionCardV4');if(!card){card=document.createElement('div');card.id='actionCardV4';card.className='action-card-v4';card.innerHTML='<h2>Hành động</h2><button id="accuseBtn" class="danger">🚨 Tố cáo Gián điệp</button><button id="guessBtn" class="secondary">🕵️ Spy đoán địa điểm</button><button id="leaveGameBtn" class="secondary">🚪 Rời phòng</button>';side.insertBefore(card,side.firstChild)}const a=$('accuseBtn'),g=$('guessBtn'),leave=$('leaveGameBtn');if(a){a.textContent='🚨 Tố cáo Gián điệp';a.disabled=false;a.onclick=()=>{if(!latest||!['game','discussion'].includes(latest.phase)||!sock)return;const others=(latest.players||[]).filter(p=>p.id!==selfId);const text=others.map((p,i)=>`${i+1}. ${p.name}`).join('\n');const n=prompt('Chọn người để tố cáo:\n'+text);const target=others[Number(n)-1];if(target)sock.emit('accuse',{targetId:target.id})}}if(g){g.textContent=guessMode?'📍 Chọn địa điểm để đoán':'🕵️ Spy đoán địa điểm';g.disabled=false;g.onclick=()=>{if(!latest||!['game','discussion'].includes(latest.phase))return;if(!isSpy){systemNotice('Chỉ Gián điệp mới có thể đoán địa điểm.');return}guessMode=!guessMode;g.classList.toggle('active',guessMode);g.textContent=guessMode?'📍 Chọn địa điểm để đoán':'🕵️ Spy đoán địa điểm';if(guessMode)systemNotice('🕵️ Spy đang chọn địa điểm trên bảng. Hãy bấm vào một ảnh.')}}if(leave)leave.onclick=leaveRoom}
function systemNotice(t){const box=$('chatLog');if(!box)return;const d=document.createElement('div');d.className='chat-system';d.textContent=t;box.appendChild(d);box.scrollTop=box.scrollHeight}
function patchChat(){const input=$('chatInput'),btn=$('chatSendBtn');if(!input||!btn)return;const active=!!latest&&['game','discussion'].includes(latest.phase);input.disabled=!active;btn.disabled=!active;input.placeholder=active?'Nhập tin nhắn...':'Chat đã kết thúc';const send=()=>{const text=input.value.trim();if(!text||!active||!sock)return;sock.emit('chat_message',{message:text});input.value='';input.focus()};btn.onclick=send;input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();send()}}}
function patchLobby(){const list=$('playerList');if(!list||!latest)return;list.querySelectorAll('.player').forEach((el,i)=>{const p=latest.players[i];if(!p)return;el.dataset.playerId=p.id;let b=el.querySelector('.kick-btn');if(latest.hostId===selfId&&p.id!==selfId&&latest.phase==='lobby'){if(!b){b=document.createElement('button');b.className='kick-btn';b.textContent='Kick';b.onclick=e=>{e.stopPropagation();if(confirm(`Kick ${p.name} khỏi phòng?`))sock.emit('kick_player',{targetId:p.id})};el.appendChild(b)}}else if(b)b.remove()})}
function patchResult(r){const card=document.querySelector('.result-card');if(!card)return;let box=$('roundWinnerBox');if(!box){box=document.createElement('div');box.id='roundWinnerBox';box.className='round-winner-box';const scores=$('resultScores');card.insertBefore(box,scores)}const names=r.winnerNames?.length?r.winnerNames.join(', '):'Không xác định';const deltas=r.roundDeltas||{};const rows=(latest?.players||[]).map(p=>{const d=Number(deltas[p.id]||0);return d?`<div><span>${esc(p.name)}</span><strong>${d>0?'+':''}${d} điểm</strong></div>`:''}).filter(Boolean).join('');box.innerHTML=`<div class="winner-title">🏆 Người chiến thắng vòng</div><div class="winner-names">${esc(names)}</div><div class="winner-points">${rows||'Không có điểm cộng.'}</div>`}
function leaveRoom(){if(sock)sock.emit('leave_room');setTimeout(()=>location.reload(),100)}
function boot(){sock=io();sock.on('watch_ready',x=>{selfId=x.selfId;window.spyfallSelfName=x.name});sock.on('role',r=>{isSpy=!!r.spy});sock.on('room_state',s=>{latest=s;patchChat();ensureActionButtons();patchLobby();if(s.phase!=='game'&&s.phase!=='discussion')guessMode=false});sock.on('round_result',r=>{setTimeout(()=>patchResult(r),30)});sock.on('kicked',m=>{alert(m||'Bạn đã bị Host đuổi khỏi phòng.');location.reload()});sock.on('error_msg',m=>systemNotice(m));setInterval(()=>{const code=roomCode(),name=playerName();if(code&&name&&!selfId)sock.emit('watch_room',{code,name})},700);const obs=new MutationObserver(()=>{ensureActionButtons();patchChat();patchLobby()});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{if(!guessMode||!isSpy||!latest||!['game','discussion'].includes(latest.phase))return;const card=e.target.closest('.location-card');if(!card)return;e.preventDefault();e.stopImmediatePropagation();const location=card.dataset.location;if(location){guessMode=false;const g=$('guessBtn');if(g){g.classList.remove('active');g.textContent='🕵️ Spy đoán địa điểm'}sock.emit('spy_guess_location',{location})}},true);const leaveBtn=$('leaveBtn');if(leaveBtn)leaveBtn.onclick=leaveRoom}
boot();})();