(()=>{
let sock=null,selfId=null,isSpy=false,latest=null,selectedTarget='';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]));
function inject(){if(document.getElementById('sharedChatCard'))return;const side=document.querySelector('.side-actions');if(!side)return;side.innerHTML=`<div id="sharedChatCard" class="shared-chat-card"><div class="shared-chat-head"><div><h2>💬 Chat chung</h2><div class="muted small">Trao đổi realtime trong suốt ván chơi</div></div><span id="chatPhasePill" class="pill">ĐANG HỎI</span></div><div id="chatLog" class="chat-log"></div><div class="chat-compose"><input id="chatInput" maxlength="300" placeholder="Nhập tin nhắn..." autocomplete="off"><button id="chatSendBtn">Gửi</button></div></div><div id="actionCard" class="action-card"><div class="eyebrow">HÀNH ĐỘNG</div><button id="accuseNowBtn" class="danger">🚨 Tố cáo Gián điệp</button><button id="spyGuessUi" class="secondary">🕵️ Spy đoán địa điểm</button><p id="actionHint" class="muted small">Bất cứ người chơi nào cũng có thể tố cáo.</p></div><div id="voteCard" class="vote-card"><div class="eyebrow">THẢO LUẬN</div><h3>Chọn người nghi là Spy</h3><p class="muted small">Sau khi thảo luận, mỗi người chọn 1 người. Người được chọn nhiều nhất bị tố cáo.</p><div id="voteList" class="vote-list"></div></div><div id="scoreSideCard" class="score-side-card"><h3>Điểm</h3><div id="scoreSideList"></div></div>`;
const send=()=>{const input=$('chatInput'),text=input?.value.trim();if(!sock||!text||!['game','discussion'].includes(latest?.phase))return;sock.emit('chat_message',{message:text});input.value='';input.focus()};$('chatSendBtn').onclick=send;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();send()}});
$('accuseNowBtn').onclick=()=>{if(!sock||!['game','discussion'].includes(latest?.phase))return;const others=(latest.players||[]).filter(p=>p.id!==selfId);const n=prompt('Đại diện tố cáo — chọn số người:\n'+others.map((p,i)=>`${i+1}. ${p.name}`).join('\n'));const target=others[Number(n)-1];if(target)sock.emit('accuse',{targetId:target.id})};
$('spyGuessUi').onclick=()=>{if(!isSpy||!sock||!['game','discussion'].includes(latest?.phase))return;alert('Spy: hãy bấm trực tiếp vào địa điểm trên bảng để đoán.');};
}
function styleQuestionPanel(){const box=document.querySelector('.question-box');if(!box||!latest)return;let chooser=document.getElementById('targetChooser');if(!chooser){chooser=document.createElement('div');chooser.id='targetChooser';chooser.className='target-chooser';box.parentNode.insertBefore(chooser,box)}const sel=$('targetSelect');if(sel)sel.style.display='none';const candidates=(latest.players||[]).filter(p=>p.id!==selfId&&!(latest.askedIds||[]).includes(p.id)&&p.id!==latest.lastQuestionerId);if(!candidates.some(p=>p.id===selectedTarget))selectedTarget='';chooser.innerHTML=`<div class="chooser-title">Chọn người chơi</div><div class="target-buttons">${candidates.length?candidates.map(p=>`<button type="button" class="target-btn ${selectedTarget===p.id?'selected':''}" data-id="${p.id}">${esc(p.name)}</button>`).join(''):'<span class="muted small">Không còn người phù hợp</span>'}</div>`;chooser.querySelectorAll('.target-btn').forEach(b=>b.onclick=()=>{selectedTarget=b.dataset.id;if(sel)sel.value=selectedTarget;chooser.querySelectorAll('.target-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');updateQuestionState()});updateQuestionState()}
function updateQuestionState(){const myTurn=latest?.phase==='game'&&latest.players?.[latest.turnIndex]?.id===selfId;const ok=myTurn&&!!selectedTarget&&!latest.pending;$('questionInput').disabled=!ok;$('sendQuestionBtn').disabled=!ok;let text='';if(latest?.phase==='discussion')text='Tất cả người chơi đã hỏi xong. Hãy trao đổi ở Chat chung rồi cùng chọn người nghi là Spy.';else if(latest?.pending){const from=(latest.players||[]).find(p=>p.id===latest.pending.fromId),to=(latest.players||[]).find(p=>p.id===latest.pending.toId);text=`${from?.name||''} → ${to?.name||''}: đang chờ trả lời.`}else if(myTurn)text='Chọn một người chơi để đặt câu hỏi. Mỗi người chỉ được hỏi 1 lần trong vòng.';else if(latest?.pending&&latest.pending.toId===selfId)text='Trả lời câu hỏi bên dưới.';else text='Chờ người đang có lượt.';$('turnInstruction').textContent=text;const turnLabel=$('turnLabel');if(turnLabel){if(latest?.pending){const from=(latest.players||[]).find(p=>p.id===latest.pending.fromId),to=(latest.players||[]).find(p=>p.id===latest.pending.toId);turnLabel.textContent=`${from?.name||''} → ${to?.name||''}`}else{const current=latest?.players?.[latest.turnIndex];turnLabel.textContent=latest?.phase==='discussion'?'THẢO LUẬN':myTurn?'LƯỢT CỦA BẠN':`LƯỢT: ${current?.name||''}`}}}
function renderHistory(){const log=$('qaLog');if(!log||!latest)return;log.innerHTML=latest.qa?.length?latest.qa.map((x,i)=>`<div class="qa-item v3"><div class="qa-number">${i+1}</div><div class="qa-body"><div class="qa-meta"><strong>${esc(x.from)}</strong> <span>→</span> <strong>${esc(x.to)}</strong></div><div><strong>Hỏi:</strong> ${esc(x.q)}</div><div class="answer-line"><strong>Trả lời:</strong> ${esc(x.a)}</div></div></div>`).join(''):'<div class="muted small">Chưa có câu hỏi nào.</div>';log.scrollTop=log.scrollHeight}
function renderChat(){const log=$('chatLog');if(!log||!latest)return;log.innerHTML=(latest.chat||[]).map(x=>`<div class="chat-item ${x.from===window.spyfallSelfName?'mine':''} ${x.system?'system':''}"><div class="chat-author">${esc(x.from||'Hệ thống')}</div><div class="chat-text">${esc(x.message)}</div></div>`).join('')||'<div class="muted small chat-empty">Chưa có tin nhắn. Hãy bắt đầu trao đổi!</div>';log.scrollTop=log.scrollHeight}
function renderVotes(){const list=$('voteList');if(!list||!latest)return;const votes=latest.votes||{};const counts=Object.values(votes);list.innerHTML=(latest.players||[]).filter(p=>p.id!==selfId).map(p=>`<button type="button" class="vote-btn ${votes[selfId]===p.id?'voted':''}" data-id="${p.id}">${esc(p.name)}<span>${counts.filter(x=>x===p.id).length||''}</span></button>`).join('');list.querySelectorAll('.vote-btn').forEach(b=>b.onclick=()=>{if(latest.phase==='discussion')sock.emit('accuse_vote',{targetId:b.dataset.id})});$('voteCard').style.display=latest.phase==='discussion'?'block':'none'}
function renderScores(){const el=$('scoreSideList');if(!el||!latest)return;el.innerHTML=(latest.players||[]).map(p=>`<div class="score-row"><span>${esc(p.name)}</span><strong>${latest.scores?.[p.id]||0}</strong></div>`).join('')}
function renderActions(){if(!latest)return;const a=$('actionCard'),acc=$('accuseNowBtn'),guess=$('spyGuessUi'),hint=$('actionHint');if(!a)return;const active=['game','discussion'].includes(latest.phase);a.style.display=active?'block':'none';if(acc)acc.disabled=!active;if(guess){guess.style.display=isSpy&&active?'block':'none';guess.disabled=!isSpy||!active}if(hint)hint.textContent=isSpy?'Bấm một địa điểm trên bảng để Spy đoán bất cứ lúc nào.':'Bất cứ người chơi nào cũng có thể tố cáo bất cứ lúc nào.'}
function render(s){latest=s;inject();styleQuestionPanel();renderHistory();renderChat();renderVotes();renderScores();renderActions();const active=['game','discussion'].includes(s.phase),input=$('chatInput'),btn=$('chatSendBtn');if(input&&btn){input.disabled=!active;btn.disabled=!active;input.placeholder='Nhập tin nhắn...'}if($('chatPhasePill'))$('chatPhasePill').textContent=s.phase==='discussion'?'THẢO LUẬN':s.phase==='game'?'ĐANG HỎI':'KẾT THÚC';}
function connectActiveRoom(){if(!sock)return;const code=($('gameRoomCode')?.textContent||'').trim(),name=($('playerName')?.value||'').trim();if(!selfId&&/^[A-Z0-9]{4,8}$/.test(code)&&name)sock.emit('watch_room',{code,name})}
function bindSpyLocation(){document.querySelectorAll('.location-card').forEach(card=>{if(card.dataset.spyBound)return;card.dataset.spyBound='1';card.addEventListener('click',e=>{if(!isSpy||!latest||!['game','discussion'].includes(latest.phase))return;const location=card.dataset.location;if(!location)return;e.stopPropagation();if(confirm(`Spy đoán địa điểm này?\n\n${location}`))sock.emit('spy_guess_location',{location})},true)})}
function boot(){sock=io();sock.on('watch_ready',x=>{selfId=x.selfId;window.spyfallSelfName=x.name});sock.on('role',r=>{isSpy=!!r.spy;renderActions();bindSpyLocation()});sock.on('room_state',s=>{render(s);setTimeout(bindSpyLocation,0)});window.spyfallSelfName=($('playerName')?.value||'').trim();setInterval(connectActiveRoom,500);const obs=new MutationObserver(()=>{if(document.querySelector('.screen.active')?.id==='gameScreen'){inject();connectActiveRoom();bindSpyLocation()}});obs.observe(document.body,{childList:true,subtree:true})}
boot();
})();