(()=>{
let sock=null,selfId=null,isSpy=false,latest=null,selectedTarget='';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]));
function inject(){if(document.getElementById('sharedChatCard'))return;const grid=document.querySelector('.game-grid');if(!grid)return;const side=document.querySelector('.side-actions');if(!side)return;side.innerHTML=`<div id="sharedChatCard" class="shared-chat-card"><div class="shared-chat-head"><div><h2>💬 Chat chung</h2><div class="muted small">Trao đổi sau khi mọi người đã hỏi xong</div></div><span id="chatPhasePill" class="pill">THẢO LUẬN</span></div><div id="chatLog" class="chat-log"></div><div class="chat-compose"><input id="chatInput" maxlength="300" placeholder="Nhập tin nhắn..." autocomplete="off"><button id="chatSendBtn">Gửi</button></div></div><div id="voteCard" class="vote-card"><div class="eyebrow">QUYẾT ĐỊNH</div><h3>Chọn gián điệp</h3><p class="muted small">Sau khi trao đổi, mỗi người chọn 1 người mà mình nghi là Spy.</p><div id="voteList" class="vote-list"></div><button id="spyGuessUi" class="secondary">🕵️ Spy đoán địa điểm</button></div><div id="scoreSideCard" class="score-side-card"><h3>Điểm</h3><div id="scoreSideList"></div></div>`;
const send=()=>{const input=$('chatInput');if(!input||!sock)return;const text=input.value.trim();if(!text)return;sock.emit('chat_message',{message:text});input.value='';input.focus()};$('chatSendBtn').onclick=send;$('chatInput').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}});$('spyGuessUi').onclick=()=>{if(!isSpy||!sock)return;const g=prompt('Spy đoán địa điểm:');if(g?.trim())sock.emit('spy_guess',{guess:g.trim()})};
}
function styleQuestionPanel(){const card=document.querySelector('.game-grid>.card');if(!card)return;let chooser=document.getElementById('targetChooser');if(!chooser){const box=document.querySelector('.question-box');if(!box)return;chooser=document.createElement('div');chooser.id='targetChooser';chooser.className='target-chooser';box.parentNode.insertBefore(chooser,box)};const sel=$('targetSelect');if(sel){sel.style.display='none';}const candidates=(latest?.players||[]).filter(p=>p.id!==selfId&&!(latest?.askedIds||[]).includes(p.id)&&p.id!==latest?.lastQuestionerId);chooser.innerHTML=`<div class="chooser-title">Chọn người chơi</div><div class="target-buttons">${candidates.length?candidates.map(p=>`<button type="button" class="target-btn ${selectedTarget===p.id?'selected':''}" data-id="${p.id}">${esc(p.name)}</button>`).join(''):'<span class="muted small">Không còn người phù hợp</span>'}</div>`;chooser.querySelectorAll('.target-btn').forEach(b=>b.onclick=()=>{selectedTarget=b.dataset.id;chooser.querySelectorAll('.target-btn').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');if(sel)sel.value=selectedTarget;updateQuestionState()});updateQuestionState()}
function updateQuestionState(){const myTurn=latest?.players?.[latest.turnIndex]?.id===selfId&&latest.phase==='game';const hasTarget=!!selectedTarget;$('questionInput').disabled=!myTurn||!hasTarget;$('sendQuestionBtn').disabled=!myTurn||!hasTarget;$('turnInstruction').textContent=latest?.phase==='discussion'?'Tất cả người chơi đã hỏi xong. Hãy trao đổi ở Chat chung rồi chọn gián điệp.':myTurn?'Chọn một người chơi để đặt câu hỏi. Mỗi người chỉ được hỏi 1 lần trong vòng.':latest?.pendingAnswer?'Trả lời câu hỏi bên dưới.':'Chờ người đang có lượt.'}
function renderHistory(){const log=$('qaLog');if(!log||!latest)return;log.innerHTML=latest.qa?.length?latest.qa.map((x,i)=>`<div class="qa-item v3"><div class="qa-number">${i+1}</div><div class="qa-body"><div class="qa-meta"><strong>${esc(x.from)}</strong> <span>→</span> <strong>${esc(x.to)}</strong></div><div><strong>Hỏi:</strong> ${esc(x.q)}</div><div class="answer-line"><strong>Trả lời:</strong> ${esc(x.a)}</div></div></div>`).join(''):'<div class="muted small">Chưa có câu hỏi nào.</div>';log.scrollTop=log.scrollHeight}
function renderChat(){const log=$('chatLog');if(!log||!latest)return;log.innerHTML=(latest.chat||[]).map(x=>`<div class="chat-item ${x.from===window.spyfallSelfName?'mine':''}"><div class="chat-author">${esc(x.from)}</div><div class="chat-text">${esc(x.message)}</div></div>`).join('')||'<div class="muted small chat-empty">Chưa có tin nhắn. Hãy bắt đầu trao đổi!</div>';log.scrollTop=log.scrollHeight}
function renderVotes(){const list=$('voteList');if(!list||!latest)return;const votes=latest.votes||{};const all=latest.players||[];list.innerHTML=all.filter(p=>p.id!==selfId).map(p=>`<button type="button" class="vote-btn ${Object.values(votes).includes(p.id)?'voted':''}" data-id="${p.id}">${esc(p.name)}<span>${Object.values(votes).filter(x=>x===p.id).length||''}</span></button>`).join('');list.querySelectorAll('.vote-btn').forEach(b=>b.onclick=()=>{if(latest.phase!=='discussion')return;sock.emit('accuse_vote',{targetId:b.dataset.id})});$('voteCard').style.display=latest.phase==='discussion'?'block':'none';$('spyGuessUi').style.display=isSpy&&latest.phase==='discussion'?'block':'none'}
function renderScores(){const el=$('scoreSideList');if(!el||!latest)return;el.innerHTML=(latest.players||[]).map(p=>`<div class="score-row"><span>${esc(p.name)}</span><strong>${latest.scores?.[p.id]||0}</strong></div>`).join('')}
function render(s){latest=s;inject();styleQuestionPanel();renderHistory();renderChat();renderVotes();renderScores();if(s.phase==='discussion'){document.getElementById('targetChooser')?.classList.add('disabled');$('questionInput').disabled=true;$('sendQuestionBtn').disabled=true;$('chatInput').focus();$('chatPhasePill').textContent='THẢO LUẬN'}else if(s.phase==='game'){$('chatPhasePill').textContent='ĐANG HỎI'}else if(s.phase==='result'){$('chatPhasePill').textContent='KẾT THÚC'}}
function boot(){sock=window.spyfallSocket;if(!sock){setTimeout(boot,100);return}sock.on('joined',x=>{selfId=x.selfId});sock.on('role',r=>{isSpy=!!r.spy});sock.on('room_state',render);sock.on('question_received',()=>setTimeout(()=>{styleQuestionPanel()},30));window.spyfallSelfName='';const obs=new MutationObserver(()=>{const el=document.querySelector('.screen.active');if(el?.id==='gameScreen')inject()});obs.observe(document.body,{childList:true,subtree:true})}
boot();
})();