(()=>{
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
function getLocations(){try{return Array.isArray(state?.locations)?state.locations:[]}catch(_){return []}}
function getFiles(){try{return Array.isArray(state?.locationFiles)?state.locationFiles:[]}catch(_){return []}}
function srcFor(name,index){const files=getFiles();const file=files[index];return `/assets/${encodeURIComponent(file||String(name).replace(/ /g,'_')+'.webp')}`}
function renderBoard(){const grid=document.getElementById('locationGrid');if(!grid)return;const locations=getLocations();if(!locations.length)return;const files=getFiles();const key=locations.join('|')+'||'+files.join('|');if(grid.dataset.key===key)return;grid.dataset.key=key;grid.innerHTML=locations.map((name,i)=>`<button type="button" class="location-card" data-location="${esc(name)}" data-number="${i+1}" title="${esc(name)}" aria-label="${i+1}. ${esc(name)}" style="background-image:url('${srcFor(name,i)}')"></button>`).join('');grid.querySelectorAll('.location-card').forEach(card=>card.addEventListener('click',()=>openModal(card.dataset.location,Number(card.dataset.number)-1)))}
function openModal(name,index){const modal=document.getElementById('locationModal'),img=document.getElementById('locationModalImage'),label=document.getElementById('locationModalName');if(!modal||!img||!label)return;label.textContent=name;img.style.backgroundImage=`url("${srcFor(name,index)}")`;img.alt=name;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function closeModal(){const modal=document.getElementById('locationModal');if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
function hook(){if(typeof renderGame!=='function')return setTimeout(hook,50);const original=renderGame;renderGame=function(){original();renderBoard()};document.getElementById('locationModal')?.addEventListener('click',e=>{if(e.target.id==='locationModal'||e.target.id==='locationModalImage'||e.target.closest('#locationModalImage'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});renderBoard()}
hook();
})();