(()=>{
const esc=s=>String(s??'').replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
const DISPLAY_NAMES={'Bai bien':'Bãi biển','Bai dap truc thang':'Bãi đáp trực thăng','Bao tang':'Bảo tàng','Ben du thuyen':'Bến du thuyền','Ben xe':'Bến xe','Benh vien':'Bệnh viện','Can cu quan su':'Căn cứ quân sự','Can phong bi mat':'Căn phòng bí mật','Cang bien':'Cảng biển','Cong truong xay dung':'Công trường xây dựng','Cong vien giai tri':'Công viên giải trí','Cong vien nuoc':'Công viên nước','Cua hang trang suc':'Cửa hàng trang sức','Dai hoc':'Đại học','Dai su quan':'Đại sứ quán','Dai truyen hinh':'Đài truyền hình','Dao hoang':'Đảo hoang','Den co':'Đền cổ','Don canh sat':'Đồn cảnh sát','Ga tau dien':'Ga tàu điện','Ga tau dien ngam':'Ga tàu điện ngầm','Hang phim':'Hãng phim','Ho boi':'Hồ bơi','Khach san':'Khách sạn','Kho hang':'Kho hàng','Khu cam trai':'Khu cắm trại','Khu khao co':'Khu khảo cổ','Khu nghi duong':'Khu nghỉ dưỡng','Khu rung':'Khu rừng','Khu truot tuyet':'Khu trượt tuyết','Lau dai':'Lâu đài','Leu ganh xiec':'Lều gánh xiếc','May bay':'Máy bay','Ngan hang':'Ngân hàng','Nha bep nha hang':'Nhà bếp nhà hàng','Nha hang':'Nhà hàng','Nha may':'Nhà máy','Nha tho':'Nhà thờ','Nui lua':'Núi lửa','Phong gym':'Phòng gym','Phong thi nghiem':'Phòng thí nghiệm','Phong thu am':'Phòng thu âm','Phong trien lam nghe thuat':'Phòng triển lãm nghệ thuật','Quan Thap Tu':'Quân Thập Tự','Rap chieu phim':'Rạp chiếu phim','Rap hat':'Rạp hát','Rap xiec':'Rạp xiếc','Sa mac':'Sa mạc','San bay':'Sân bay','San van dong':'Sân vận động','Sieu thi':'Siêu thị','So thu':'Sở thú','Song bac':'Sòng bạc','Spa':'Spa','Tau cuop bien':'Tàu cướp biển','Tau du lich':'Tàu du lịch','Tau hoa':'Tàu hỏa','Tau ngam':'Tàu ngầm','Thap quan sat':'Tháp quan sát','Thu vien':'Thư viện','Tiec cong ty':'Tiệc công ty','Toa an':'Tòa án','Toa soan bao':'Tòa soạn báo','Tram Bac Cuc':'Trạm Bắc Cực','Tram cuu hoa':'Trạm cứu hỏa','Tram dich vu':'Trạm dịch vụ','Tram vu tru':'Trạm vũ trụ','Tram xang':'Trạm xăng','Trung tam nghien cuu':'Trung tâm nghiên cứu','Truong dua xe':'Trường đua xe','Truong hoc':'Trường học'};
function getLocations(){try{return Array.isArray(state?.locations)?state.locations:[]}catch(_){return []}}
function getFiles(){try{return Array.isArray(state?.locationFiles)?state.locationFiles:[]}catch(_){return []}}
function displayName(name){return DISPLAY_NAMES[name]||name}
function srcFor(name,index){const files=getFiles();const file=files[index];return `/assets/${encodeURIComponent(file||String(name).replace(/ /g,'_')+'.webp')}`}
function renderBoard(){const grid=document.getElementById('locationGrid');if(!grid)return;const locations=getLocations();if(!locations.length)return;const files=getFiles();const key=locations.join('|')+'||'+files.join('|');if(grid.dataset.key===key)return;grid.dataset.key=key;grid.innerHTML=locations.map((name,i)=>{const label=displayName(name),src=srcFor(name,i);return `<button type="button" class="location-card" data-location="${esc(name)}" data-number="${i+1}" title="${esc(label)}" aria-label="${i+1}. ${esc(label)}" style="background-image:url('${src}')"><img src="${src}" alt="${esc(label)}" loading="eager" decoding="async" style="display:block;width:100%;height:100%;object-fit:cover;border-radius:inherit" onerror="this.style.display='none'"></button>`}).join('');grid.querySelectorAll('.location-card').forEach(card=>card.addEventListener('click',()=>openModal(card.dataset.location,Number(card.dataset.number)-1)))}
function openModal(name,index){const modal=document.getElementById('locationModal'),img=document.getElementById('locationModalImage'),label=document.getElementById('locationModalName');if(!modal||!img||!label)return;const display=displayName(name);label.textContent=display;img.src=srcFor(name,index);img.style.backgroundImage='none';img.alt=display;modal.classList.add('show');modal.setAttribute('aria-hidden','false')}
function closeModal(){const modal=document.getElementById('locationModal');if(!modal)return;modal.classList.remove('show');modal.setAttribute('aria-hidden','true')}
function hook(){if(typeof renderGame!=='function')return setTimeout(hook,50);const original=renderGame;renderGame=function(){original();renderBoard()};document.getElementById('locationModal')?.addEventListener('click',e=>{if(e.target.id==='locationModal'||e.target.id==='locationModalImage'||e.target.closest('#locationModalImage'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});renderBoard()}
hook();
})();