const Module=require('module');
const fs=require('fs');
const original=Module._extensions['.js'];
Module._extensions['.js']=function(mod,filename){
  if(!filename.endsWith('server-v2.js'))return original(mod,filename);
  let src=fs.readFileSync(filename,'utf8');
  src=src.replace("const makeRoundLocations=(secret=null)=>{if(ALL_LOCATIONS.length<=20)return [...ALL_LOCATIONS];const others=ALL_LOCATIONS.filter(x=>x!==secret);const picked=sampleLocations(others,secret?19:20);return secret?sampleLocations([...picked,secret],20):picked};","const makeRoundLocations=(count=20,secret=null)=>{count=[20,25,30].includes(Number(count))?Number(count):20;if(ALL_LOCATIONS.length<=count)return [...ALL_LOCATIONS];const others=ALL_LOCATIONS.filter(x=>x!==secret);const picked=sampleLocations(others,secret?count-1:count);return secret?sampleLocations([...picked,secret],count):picked};");
  src=src.replace("const publicState=r=>({room:r.code,","const publicState=r=>({locationCount:r.locationCount||20,accusationGroupActive:!!r.accusationGroupActive,accusationGroupVotes:Object.fromEntries(r.accusationGroupVotes||[]),room:r.code,");
  src=src.replace("socket.on('create_room',({name,spyCount=1})=>{","socket.on('create_room',({name,spyCount=1,locationCount=20})=>{");
  src=src.replace("spyCount:sc,spyIds:[]","spyCount:sc,locationCount:[20,25,30].includes(Number(locationCount))?Number(locationCount):20,spyIds:[],accusationGroupActive:false,accusationGroupVotes:new Map()");
  src=src.replace("r.locations=makeRoundLocations();","r.locations=makeRoundLocations(r.locationCount||20);");
  src=src.replace("const scoreValue=(r,n)=>r.extraRound?(n>=2?Math.floor(n/2):0):n;","const scoreValue=(r,n)=>Number(n)||0;");
  src=src.replace("function endSpyCaught(r,initiator,target){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));award(r,initiator.id,1,d);finishRound(r,{title:'👥 Người thường thắng!',detail:`${initiator.name} tố cáo ${target.name} và xác định đúng Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}","function endSpyCaught(r,initiator,target){const d={};award(r,initiator.id,2,d);finishRound(r,{title:'👥 Người thường thắng!',detail:`${initiator.name} tố cáo ${target.name} và xác định đúng Gián điệp.`,winnerType:'nonspy',winnerNames:[initiator.name],deltas:d})}");
  src=src.replace("function accuse(r,voterId,targetId){if(!r||!['game','discussion'].includes(r.phase)||r.paused)return;const voter=r.players.find(p=>p.id===voterId),target=r.players.find(p=>p.id===targetId);if(!voter||!target||target.id===voter.id)return;addChat(r,'',`🚨 ${voter.name} tố cáo ${target.name} là Gián điệp!`);if(r.spyIds.includes(target.id))return endSpyCaught(r,voter,target);const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${voter.name} tố cáo ${target.name}, nhưng đó không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}","function accuse(r,voterId,targetId){if(!r||!['game','discussion'].includes(r.phase)||r.paused)return;const voter=r.players.find(p=>p.id===voterId),target=r.players.find(p=>p.id===targetId);if(!voter||!target||target.id===voter.id)return;addChat(r,'',`🚨 ${voter.name} tố cáo ${target.name} là Gián điệp!`);if(r.spyIds.includes(target.id))return endSpyCaught(r,voter,target);const d={};award(r,voter.id,-1,d);spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${voter.name} tố cáo ${target.name}, nhưng đó không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}");
  src=src.replace("if(actual.toLowerCase()===r.location.toLowerCase()){const d={};award(r,spy.id,4,d);return finishRound(r,{title:'🕵️ Spy thắng!',detail:`${spy.name} đoán đúng địa điểm: ${r.location}.`,winnerType:'spy',winnerNames:[spy.name],deltas:d})}const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${spy.name} đoán sai. Địa điểm là ${r.location}.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}","if(actual.toLowerCase()===r.location.toLowerCase()){const d={};award(r,spy.id,4,d);return finishRound(r,{title:'🕵️ Spy thắng!',detail:`${spy.name} đoán đúng địa điểm: ${r.location}.`,winnerType:'spy',winnerNames:[spy.name],deltas:d})}const d={};award(r,spy.id,-2,d);r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${spy.name} đoán sai. Địa điểm là ${r.location}.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}");
  src=src.replace("function finishRound(r,o){if(r.phase==='result')return;","function finishRound(r,o){if(r.phase==='result')return;r.accusationGroupActive=false;r.accusationGroupVotes=new Map();");
  src=src.replace("socket.on('set_location_count',({locationCount})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(locationCount);if([20,25,30].includes(n)){r.locationCount=n;emitRoom(r)}});","socket.on('set_location_count',({locationCount})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(locationCount);if([20,25,30].includes(n)){r.locationCount=n;emitRoom(r)}});\nsocket.on('start_group_accusation',()=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion'].includes(r.phase)||r.paused||r.accusationGroupActive)return;r.accusationGroupActive=true;r.accusationGroupVotes=new Map();addChat(r,'','🗳️ Bắt đầu tố cáo chung. Tất cả người chơi phải bỏ 1 phiếu.');io.to(r.code).emit('accusation_group_start');emitRoom(r)});\nsocket.on('group_accuse_vote',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||!r.accusationGroupActive||!['game','discussion'].includes(r.phase)||r.paused)return;const voterId=socket.playerId||socket.id;if(!r.players.some(p=>p.id===voterId)||r.accusationGroupVotes.has(voterId))return;const target=r.players.find(p=>p.id===targetId);if(!target||target.id===voterId)return;r.accusationGroupVotes.set(voterId,target.id);io.to(r.code).emit('accusation_group_state',{active:true,votes:Object.fromEntries(r.accusationGroupVotes)});emitRoom(r);if(r.accusationGroupVotes.size!==r.players.length)return;const counts={};for(const id of r.accusationGroupVotes.values())counts[id]=(counts[id]||0)+1;let max=-1,chosen=null;for(const p of r.players){const n=counts[p.id]||0;if(n>max){max=n;chosen=p.id}}const target2=r.players.find(p=>p.id===chosen);if(!target2)return;if(r.spyIds.includes(target2.id)){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${target2.name} nhận nhiều phiếu nhất và được xác định là Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}else{const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${target2.name} nhận nhiều phiếu nhất nhưng không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}});");
  mod._compile(src,filename);
};
