const express=require('express');const http=require('http');const{Server}=require('socket.io');const path=require('path');const app=express();const server=http.createServer(app);const io=new Server(server);app.use(express.static(path.join(__dirname)));app.get('/health',(_,res)=>res.json({ok:true}));
const locations=['Đại học','Sở thú','Rạp hát','Đồn cảnh sát','Câu lạc bộ đêm','Tàu biển','Tàu cướp biển','Tàu chở khách','Trạm Bắc Cực','Căn cứ quân sự','Hãng phim','Bệnh viện','Đại sứ quán','Khách sạn','Spa','Lều gánh xiếc','Quân Thập Tự','Sòng bạc','Tiệc công ty','Bãi biển','Công viên giải trí','Hội chợ','Ngân hàng','Máy bay','Siêu thị','Tàu ngầm','Trạm vũ trụ','Trạm dịch vụ','Trường học','Nhà hàng'];
const rooms=new Map();const makeCode=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};const spiesOf=r=>r.players.filter(p=>r.spyIds.includes(p.id));const publicState=r=>({room:r.code,players:r.players.map(p=>({id:p.id,name:p.name,score:p.score})),hostId:r.hostId,phase:r.phase,round:r.round,turnIndex:r.turnIndex,timer:Math.max(0,Math.ceil((r.endsAt-Date.now())/1000)),qa:r.qa,scores:Object.fromEntries(r.players.map(p=>[p.id,p.score])),locations,askedIds:[...r.askedIds],lastQuestionerId:r.lastQuestionerId,chat:r.chat||[],votes:Object.fromEntries(r.votes||[]),pending:r.pending?{fromId:r.pending.fromId,toId:r.pending.toId,q:r.pending.q}:null,spyCount:r.spyCount,winScore:r.winScore,matchOver:!!r.matchOver,matchWinners:r.matchWinners||[]});
const emitRoom=r=>io.to(r.code).emit('room_state',publicState(r));function addChat(r,from,message){r.chat.push({from,message,time:Date.now(),system:!from});if(r.chat.length>100)r.chat.shift()}function award(r,id,n,d){const p=r.players.find(x=>x.id===id);if(p&&n){p.score+=n;d[id]=(d[id]||0)+n}}
function finishRound(r,o){if(r.phase==='result')return;r.phase='result';if(r.timerId)clearTimeout(r.timerId);if(r.noticeTimer)clearTimeout(r.noticeTimer);const winners=r.players.filter(p=>p.score>=r.winScore);if(winners.length&&!r.matchOver){r.matchOver=true;r.matchWinners=winners.map(p=>p.id);o.detail+=` ${winners.map(p=>p.name).join(', ')} đã đạt ${r.winScore} điểm và thắng toàn bộ game!`}const scores=Object.fromEntries(r.players.map(p=>[p.id,p.score]));const deltaNames=Object.fromEntries(r.players.map(p=>[p.id,o.deltas?.[p.id]||0]));io.to(r.code).emit('round_result',{title:o.title,detail:o.detail,location:r.location,spyIds:r.spyIds,scores,winnerType:o.winnerType,winnerNames:o.winnerNames||[],roundDeltas:deltaNames,matchOver:r.matchOver,matchWinners:r.matchWinners||[],winScore:r.winScore||r.winScore});emitRoom(r)}
function endSpyCaught(r,initiator,target){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));award(r,initiator.id,1,d);finishRound(r,{title:'👥 Người thường thắng!',detail:`${initiator.name} tố cáo ${target.name} và xác định đúng Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}
function accuse(r,voterId,targetId){if(!r||!['game','discussion'].includes(r.phase))return;const voter=r.players.find(p=>p.id===voterId),target=r.players.find(p=>p.id===targetId);if(!voter||!target||target.id===voter.id)return;if(r.spyIds.includes(voter.id))return;addChat(r,'',`🚨 ${voter.name} tố cáo ${target.name} là Gián điệp!`);if(r.spyIds.includes(target.id))return endSpyCaught(r,voter,target);const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${voter.name} tố cáo ${target.name}, nhưng đó không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}
function spyGuess(r,spyId,guess){if(!r||!['game','discussion'].includes(r.phase)||!r.spyIds.includes(spyId))return;const spy=r.players.find(p=>p.id===spyId),g=String(guess||'').trim();if(!spy||!g)return;addChat(r,'',`🎯 ${spy.name} đã đoán địa điểm: ${g}`);if(g.toLowerCase()===r.location.toLowerCase()){const d={};award(r,spy.id,4,d);return finishRound(r,{title:'🕵️ Spy thắng!',detail:`${spy.name} đoán đúng địa điểm: ${r.location}.`,winnerType:'spy',winnerNames:[spy.name],deltas:d})}const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${spy.name} đoán sai. Địa điểm là ${r.location}.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}
function resolveVote(r,targetId){if(!['game','discussion'].includes(r.phase))return;const counts={};for(const id of r.votes.values())counts[id]=(counts[id]||0)+1;const n=counts[targetId]||0;if(n<Math.ceil(r.players.length/2))return;const target=r.players.find(p=>p.id===targetId);if(!target)return;if(r.spyIds.includes(target.id)){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${target.name} nhận đủ ${n} phiếu và bị xác định là Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}else{const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${target.name} nhận đủ ${n} phiếu nhưng không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}}
function startRound(r){if(r.players.length<3)return;r.phase='game';r.round++;r.location=locations[Math.floor(Math.random()*locations.length)];r.spyIds=[];const pool=[...r.players];for(let i=0;i<r.spyCount;i++){const j=Math.floor(Math.random()*pool.length);r.spyIds.push(pool.splice(j,1)[0].id)}r.turnIndex=Math.floor(Math.random()*r.players.length);r.qa=[];r.chat=[];r.votes=new Map();r.pending=null;r.askedIds=new Set();r.lastQuestionerId=null;r.endsAt=Date.now()+600000;if(r.timerId)clearTimeout(r.timerId);if(r.noticeTimer)clearTimeout(r.noticeTimer);r.noticeTimer=setTimeout(()=>{if(['game','discussion'].includes(r.phase)){addChat(r,'','⏰ Còn 2 phút! Hãy nhanh chóng tìm Gián điệp hoặc để Spy đoán địa điểm.');emitRoom(r)}},480000);r.timerId=setTimeout(()=>{const d={};spiesOf(r).forEach(p=>award(r,p.id,2,d));addChat(r,'','⏰ Hết thời gian! Chưa có ai bắt được Spy.');finishRound(r,{title:'🕵️ Spy thắng!',detail:'Hết 10 phút mà chưa có ai bắt được Spy. Mỗi Spy nhận 2 điểm.',winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})},600000);for(const p of r.players)io.to(p.id).emit('role',{spy:r.spyIds.includes(p.id),location:r.spyIds.includes(p.id)?null:r.location,spyCount:r.spyCount});emitRoom(r)}
function enterDiscussion(r){if(r.phase!=='game')return;r.phase='discussion';r.pending=null;r.votes=new Map();addChat(r,'','💬 Tất cả người chơi đã hỏi xong. Bắt đầu thảo luận!');io.to(r.code).emit('discussion_start');emitRoom(r)}
function removePlayer(r,id){r.players=r.players.filter(p=>p.id!==id);r.askedIds.delete(id);r.votes.delete(id);if(r.hostId===id&&r.players.length)r.hostId=r.players[0].id}
io.on('connection',socket=>{
socket.on('create_room',({name,spyCount=1,winScore=5})=>{const code=makeCode();const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};const sc=Number(spyCount)===2?2:1;const ws=[5,7,10].includes(Number(winScore))?Number(winScore):5;const r={code,hostId:p.id,players:[p],phase:'lobby',round:0,turnIndex:0,qa:[],pending:null,askedIds:new Set(),lastQuestionerId:null,chat:[],votes:new Map(),spyCount:sc,winScore:ws,spyIds:[],location:null,matchOver:false,matchWinners:[]};rooms.set(code,r);socket.join(code);socket.roomCode=code;socket.playerId=socket.id;socket.emit('joined',{room:code,selfId:socket.id});emitRoom(r)});
socket.on('join_room',({code,name})=>{const r=rooms.get(String(code||'').toUpperCase());if(!r)return socket.emit('error_msg','Không tìm thấy phòng.');if(!['lobby','result'].includes(r.phase)||r.matchOver)return socket.emit('error_msg','Ván đang diễn ra hoặc game đã kết thúc.');if(r.players.length>=12)return socket.emit('error_msg','Phòng đã đủ 12 người.');const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};r.players.push(p);socket.join(r.code);socket.roomCode=r.code;socket.playerId=socket.id;socket.emit('joined',{room:r.code,selfId:socket.id});emitRoom(r)});
socket.on('set_spy_count',({spyCount})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(spyCount);if(n===1||n===2){r.spyCount=n;emitRoom(r)}});
socket.on('set_win_score',({winScore})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(winScore);if([5,7,10].includes(n)){r.winScore=n;emitRoom(r)}});
socket.on('kick_player',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id||targetId===socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t)return;io.to(t.id).emit('kicked','Bạn đã bị Host đuổi khỏi phòng.');const s=io.sockets.sockets.get(t.id);if(s){s.roomCode=null;s.disconnect(true)}removePlayer(r,targetId);emitRoom(r)});
socket.on('leave_room',()=>{const r=rooms.get(socket.roomCode);if(!r)return;const id=socket.playerId||socket.id;const wasSpy=r.spyIds.includes(id);removePlayer(r,id);socket.leave(r.code);socket.roomCode=null;if(!r.players.length){rooms.delete(r.code);return}if(r.phase==='game'&&wasSpy){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:'Một Gián điệp đã rời phòng.',winnerType:'nonspy',winnerNames:r.players.map(p=>p.name),deltas:d});return}emitRoom(r)});
socket.on('start_game',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.players.length<3||r.phase!=='lobby')return;startRound(r)});
socket.on('send_question',({targetId,question})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||r.pending||r.players[r.turnIndex]?.id!==socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t||t.id===socket.id)return;if(r.askedIds.has(t.id))return socket.emit('error_msg','Người này đã được hỏi trong vòng hiện tại.');if(r.lastQuestionerId===t.id)return socket.emit('error_msg','Không được hỏi lại người vừa hỏi mình.');const q=String(question||'').trim().slice(0,180);if(!q)return;r.pending={fromId:socket.id,toId:t.id,q};addChat(r,'',`❓ ${r.players.find(p=>p.id===socket.id).name} → ${t.name}`);io.to(t.id).emit('question_received',{fromId:socket.id,fromName:r.players.find(p=>p.id===socket.id).name,toId:t.id,q});emitRoom(r)});
socket.on('answer_question',({answer})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||!r.pending||r.pending.toId!==socket.id)return;const from=r.players.find(p=>p.id===r.pending.fromId),to=r.players.find(p=>p.id===socket.id);const a=String(answer||'').trim().slice(0,180);if(!from||!to||!a)return;r.qa.push({from:from.name,to:to.name,q:r.pending.q,a});r.askedIds.add(to.id);r.lastQuestionerId=from.id;r.pending=null;r.turnIndex=r.players.findIndex(p=>p.id===to.id);if(r.players.every(p=>r.askedIds.has(p.id)))return enterDiscussion(r);emitRoom(r)});
socket.on('chat_message',({message})=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion'].includes(r.phase))return;const p=r.players.find(x=>x.id===(socket.playerId||socket.id));const text=String(message||'').trim().slice(0,300);if(!p||!text)return;addChat(r,p.name,text);emitRoom(r)});
socket.on('accuse_vote',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion'].includes(r.phase))return;const voterId=socket.playerId||socket.id;if(!r.players.some(p=>p.id===voterId)||r.spyIds.includes(voterId))return;if(!targetId){r.votes.delete(voterId);emitRoom(r);return}const t=r.players.find(p=>p.id===targetId);if(!t||t.id===voterId)return;r.votes.set(voterId,t.id);addChat(r,'',`🗳️ ${r.players.find(p=>p.id===voterId)?.name||'Người chơi'} chọn ${t.name}.`);emitRoom(r);resolveVote(r,t.id)});
socket.on('accuse',({targetId})=>{const r=rooms.get(socket.roomCode);accuse(r,socket.playerId||socket.id,targetId)});
socket.on('spy_guess_location',({location})=>{const r=rooms.get(socket.roomCode);spyGuess(r,socket.playerId||socket.id,location)});
socket.on('next_round',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.phase!=='result'||r.matchOver)return;startRound(r)});
socket.on('disconnect',()=>{const r=rooms.get(socket.roomCode);if(!r||socket.playerId!==socket.id)return;const id=socket.id,wasSpy=r.spyIds.includes(id);removePlayer(r,id);if(!r.players.length){rooms.delete(r.code);return}if(r.phase==='game'&&wasSpy){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:'Một Gián điệp đã rời phòng.',winnerType:'nonspy',winnerNames:r.players.map(p=>p.name),deltas:d});return}emitRoom(r)})});
const PORT=process.env.PORT||3000;server.listen(PORT,()=>console.log(`Spyfall Online listening on ${PORT}`));