const express=require('express');const http=require('http');const{Server}=require('socket.io');const path=require('path');const app=express();const server=http.createServer(app);const io=new Server(server);app.use(express.static(path.join(__dirname)));app.get('/health',(_,res)=>res.json({ok:true}));
const locations=['Đại học','Sở thú','Rạp hát','Đồn cảnh sát','Câu lạc bộ đêm','Tàu biển','Tàu cướp biển','Tàu chở khách','Trạm Bắc Cực','Căn cứ quân sự','Hãng phim','Bệnh viện','Đại sứ quán','Khách sạn','Spa','Lều gánh xiếc','Quân Thập Tự','Sòng bạc','Tiệc công ty','Bãi biển','Công viên giải trí','Hội chợ','Ngân hàng','Máy bay','Siêu thị','Tàu ngầm','Trạm vũ trụ','Trạm dịch vụ','Trường học','Nhà hàng'];
const rooms=new Map();const makeCode=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};
const publicState=room=>({room:room.code,players:room.players.map(p=>({id:p.id,name:p.name,score:p.score})),hostId:room.hostId,phase:room.phase,round:room.round,turnIndex:room.turnIndex,timer:Math.max(0,Math.ceil((room.endsAt-Date.now())/1000)),qa:room.qa,scores:Object.fromEntries(room.players.map(p=>[p.id,p.score])),locations,askedIds:[...room.askedIds],lastQuestionerId:room.lastQuestionerId,chat:room.chat||[],votes:Object.fromEntries(room.votes||[]),pending:room.pending?{fromId:room.pending.fromId,toId:room.pending.toId}:null});
const emitRoom=room=>io.to(room.code).emit('room_state',publicState(room));
function addChat(room,from,message){room.chat.push({from,message,time:Date.now(),system:!from});if(room.chat.length>100)room.chat.shift()}
function finishRound(room,{title,detail,winnerType,winnerNames=[],deltas={}}){if(room.phase==='result')return;room.phase='result';if(room.timerId)clearTimeout(room.timerId);if(room.noticeTimer)clearTimeout(room.noticeTimer);const scores=Object.fromEntries(room.players.map(p=>[p.id,p.score]));const deltaNames=Object.fromEntries(room.players.map(p=>[p.id,deltas[p.id]||0]));io.to(room.code).emit('round_result',{title,detail,location:room.location,spyId:room.spyId,scores,winnerType,winnerNames,roundDeltas:deltaNames});emitRoom(room)}
function award(room,id,points,deltas){const p=room.players.find(x=>x.id===id);if(p&&points){p.score+=points;deltas[id]=(deltas[id]||0)+points}}
function endWithSpyCaught(room,initiator,target){const deltas={};room.players.filter(p=>p.id!==room.spyId).forEach(p=>award(room,p.id,1,deltas));award(room,initiator.id,1,deltas);finishRound(room,{title:'👥 Người thường thắng!',detail:`${initiator.name} tố cáo ${target.name} và xác định đúng Gián điệp.`,winnerType:'nonspy',winnerNames:room.players.filter(p=>p.id!==room.spyId).map(p=>p.name),deltas})}
function accuse(room,voterId,targetId){if(!room||!['game','discussion'].includes(room.phase))return;const voter=room.players.find(p=>p.id===voterId),target=room.players.find(p=>p.id===targetId);if(!voter||!target||target.id===voter.id)return;addChat(room,'',`🚨 ${voter.name} tố cáo ${target.name} là Gián điệp!`);if(target.id===room.spyId)return endWithSpyCaught(room,voter,target);const deltas={};const spy=room.players.find(p=>p.id===room.spyId);if(spy)award(room,spy.id,4,deltas);finishRound(room,{title:'🕵️ Spy thắng!',detail:`${voter.name} tố cáo ${target.name}, nhưng đó không phải Gián điệp.`,winnerType:'spy',winnerNames:spy?[spy.name]:[],deltas})}
function spyGuess(room,spyId,guess){if(!room||!['game','discussion'].includes(room.phase)||spyId!==room.spyId)return;const spy=room.players.find(p=>p.id===spyId),g=String(guess||'').trim();if(!spy||!g)return;addChat(room,'',`🎯 ${spy.name} đã đoán địa điểm: ${g}`);if(g.toLowerCase()===room.location.toLowerCase()){const deltas={};award(room,spy.id,4,deltas);return finishRound(room,{title:'🕵️ Spy thắng!',detail:`Spy đoán đúng địa điểm: ${room.location}.`,winnerType:'spy',winnerNames:[spy.name],deltas})}const deltas={};room.players.filter(p=>p.id!==room.spyId).forEach(p=>award(room,p.id,1,deltas));finishRound(room,{title:'👥 Người thường thắng!',detail:`Spy đoán sai. Địa điểm là ${room.location}.`,winnerType:'nonspy',winnerNames:room.players.filter(p=>p.id!==room.spyId).map(p=>p.name),deltas})}
function resolveVote(room){if(room.phase!=='discussion')return;const counts={};for(const id of room.votes.values())counts[id]=(counts[id]||0)+1;let max=0,chosen=[];for(const p of room.players){const n=counts[p.id]||0;if(n>max){max=n;chosen=[p.id]}else if(n===max&&n>0)chosen.push(p.id)}if(!chosen.length)return;const target=room.players.find(p=>p.id===chosen[0]);if(!target)return;if(target.id===room.spyId){const deltas={};room.players.filter(p=>p.id!==room.spyId).forEach(p=>award(room,p.id,1,deltas));finishRound(room,{title:'👥 Người thường thắng!',detail:`${target.name} được chọn nhiều nhất và bị xác định là Gián điệp.`,winnerType:'nonspy',winnerNames:room.players.filter(p=>p.id!==room.spyId).map(p=>p.name),deltas})}else{const deltas={};const spy=room.players.find(p=>p.id===room.spyId);if(spy)award(room,spy.id,4,deltas);finishRound(room,{title:'🕵️ Spy thắng!',detail:`${target.name} được chọn nhiều nhất nhưng không phải Gián điệp.`,winnerType:'spy',winnerNames:spy?[spy.name]:[],deltas})}}
function startRound(room){room.phase='game';room.round++;room.location=locations[Math.floor(Math.random()*locations.length)];room.spyId=room.players[Math.floor(Math.random()*room.players.length)].id;room.turnIndex=Math.floor(Math.random()*room.players.length);room.qa=[];room.chat=[];room.votes=new Map();room.pending=null;room.askedIds=new Set();room.lastQuestionerId=null;room.endsAt=Date.now()+600000;if(room.timerId)clearTimeout(room.timerId);if(room.noticeTimer)clearTimeout(room.noticeTimer);room.noticeTimer=setTimeout(()=>{if(room.phase==='game'||room.phase==='discussion'){addChat(room,'','⏰ Còn 2 phút! Hãy nhanh chóng tìm Gián điệp hoặc để Spy đoán địa điểm.');emitRoom(room)}},480000);room.timerId=setTimeout(()=>{const spy=room.players.find(p=>p.id===room.spyId);const deltas={};if(spy)award(room,spy.id,2,deltas);addChat(room,'','⏰ Hết thời gian! Chưa ai hành động, Spy thắng theo luật.');finishRound(room,{title:'🕵️ Spy thắng!',detail:'Hết 10 phút mà chưa có quyết định. Spy nhận 2 điểm.',winnerType:'spy',winnerNames:spy?[spy.name]:[],deltas})},600000);for(const p of room.players)io.to(p.id).emit('role',{spy:p.id===room.spyId,location:p.id===room.spyId?null:room.location});emitRoom(room)}
function enterDiscussion(room){if(room.phase!=='game')return;room.phase='discussion';room.pending=null;room.votes=new Map();addChat(room,'','💬 Tất cả người chơi đã hỏi xong. Bắt đầu thảo luận!');io.to(room.code).emit('discussion_start');emitRoom(room)}
io.on('connection',socket=>{
socket.on('create_room',({name})=>{const code=makeCode();const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};const room={code,hostId:p.id,players:[p],phase:'lobby',round:0,turnIndex:0,qa:[],pending:null,askedIds:new Set(),lastQuestionerId:null,chat:[],votes:new Map()};rooms.set(code,room);socket.join(code);socket.roomCode=code;socket.emit('joined',{room:code,selfId:p.id});emitRoom(room)});
socket.on('join_room',({code,name})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room)return socket.emit('error_msg','Không tìm thấy phòng.');if(!['lobby','result'].includes(room.phase))return socket.emit('error_msg','Ván đang diễn ra. Bạn có thể vào sau khi vòng kết thúc.');if(room.players.length>=12)return socket.emit('error_msg','Phòng đã đủ 12 người.');const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};room.players.push(p);socket.join(room.code);socket.roomCode=room.code;socket.emit('joined',{room:room.code,selfId:socket.id});emitRoom(room)});
socket.on('kick_player',({targetId})=>{const room=rooms.get(socket.roomCode);if(!room||room.phase!=='lobby'||room.hostId!==socket.id||targetId===socket.id)return;const target=room.players.find(p=>p.id===targetId);if(!target)return;io.to(target.id).emit('kicked','Bạn đã bị Host đuổi khỏi phòng.');const targetSocket=io.sockets.sockets.get(target.id);if(targetSocket){targetSocket.roomCode=null;targetSocket.disconnect(true)}room.players=room.players.filter(p=>p.id!==target.id);emitRoom(room)});
socket.on('leave_room',()=>{const code=socket.roomCode,room=rooms.get(code);if(!room)return;const id=socket.playerId||socket.id;room.players=room.players.filter(p=>p.id!==id);room.askedIds.delete(id);room.votes.delete(id);socket.leave(code);socket.roomCode=null;if(!room.players.length){rooms.delete(code);return}if(room.hostId===id)room.hostId=room.players[0].id;if(room.phase==='game'&&room.spyId===id){const deltas={};room.players.filter(p=>p.id!==room.spyId).forEach(p=>award(room,p.id,1,deltas));finishRound(room,{title:'👥 Người thường thắng!',detail:'Spy đã rời phòng.',winnerType:'nonspy',winnerNames:room.players.map(p=>p.name),deltas});return}emitRoom(room)});
socket.on('watch_room',({code,name})=>{const room=rooms.get(String(code||'').toUpperCase());if(!room)return;const wanted=String(name||'').trim();const p=room.players.find(x=>x.name===wanted)||room.players.find(x=>x.name.toLowerCase()===wanted.toLowerCase());if(!p)return;socket.join(room.code);socket.roomCode=room.code;socket.playerId=p.id;socket.emit('watch_ready',{selfId:p.id,name:p.name});socket.emit('room_state',publicState(room));if(room.phase==='game'||room.phase==='discussion')socket.emit('role',{spy:p.id===room.spyId,location:p.id===room.spyId?null:room.location})});
socket.on('start_game',()=>{const room=rooms.get(socket.roomCode);if(!room||room.hostId!==socket.id||room.players.length<3)return;startRound(room)});
socket.on('send_question',({targetId,question})=>{const room=rooms.get(socket.roomCode);if(!room||room.phase!=='game'||room.pending||room.players[room.turnIndex]?.id!==socket.id)return;const target=room.players.find(p=>p.id===targetId);if(!target||target.id===socket.id)return;if(room.askedIds.has(target.id))return socket.emit('error_msg','Người này đã được hỏi trong vòng hiện tại.');if(room.lastQuestionerId===target.id)return socket.emit('error_msg','Không được hỏi lại người vừa hỏi bạn.');const q=String(question||'').trim().slice(0,180);if(!q)return;room.pending={fromId:socket.id,toId:target.id,q};addChat(room,'',`❓ ${room.players.find(p=>p.id===socket.id).name} → ${target.name}`);io.to(target.id).emit('question_received',{fromId:socket.id,fromName:room.players.find(p=>p.id===socket.id).name,q});emitRoom(room)});
socket.on('answer_question',({answer})=>{const room=rooms.get(socket.roomCode);if(!room||room.phase!=='game'||!room.pending||room.pending.toId!==socket.id)return;const from=room.players.find(p=>p.id===room.pending.fromId);const to=room.players.find(p=>p.id===socket.id);const a=String(answer||'').trim().slice(0,180);if(!from||!to||!a)return;room.qa.push({from:from.name,to:to.name,q:room.pending.q,a});room.askedIds.add(to.id);room.lastQuestionerId=from.id;room.pending=null;room.turnIndex=room.players.findIndex(p=>p.id===to.id);if(room.players.every(p=>room.askedIds.has(p.id)))return enterDiscussion(room);emitRoom(room)});
socket.on('chat_message',({message})=>{const room=rooms.get(socket.roomCode);if(!room||!['game','discussion'].includes(room.phase))return;const p=room.players.find(x=>x.id===(socket.playerId||socket.id));const text=String(message||'').trim().slice(0,300);if(!p||!text)return;addChat(room,p.name,text);emitRoom(room)});
socket.on('accuse_vote',({targetId})=>{const room=rooms.get(socket.roomCode);if(!room||room.phase!=='discussion')return;const voterId=socket.playerId||socket.id;if(!room.players.some(p=>p.id===voterId))return;const target=room.players.find(p=>p.id===targetId);if(!target||target.id===voterId)return;room.votes.set(voterId,target.id);addChat(room,'',`🗳️ ${room.players.find(p=>p.id===voterId)?.name||'Người chơi'} chọn ${target.name}.`);emitRoom(room);if(room.votes.size===room.players.length)resolveVote(room)});
socket.on('accuse',({targetId})=>{const room=rooms.get(socket.roomCode);accuse(room,socket.playerId||socket.id,targetId)});
socket.on('spy_guess',({guess})=>{const room=rooms.get(socket.roomCode);spyGuess(room,socket.playerId||socket.id,guess)});
socket.on('spy_guess_location',({location})=>{const room=rooms.get(socket.roomCode);spyGuess(room,socket.playerId||socket.id,location)});
socket.on('next_round',()=>{const room=rooms.get(socket.roomCode);if(!room||room.hostId!==socket.id||room.phase!=='result')return;startRound(room)});
socket.on('disconnect',()=>{const code=socket.roomCode,room=rooms.get(code);if(!room||socket.playerId)return;room.players=room.players.filter(p=>p.id!==socket.id);room.askedIds.delete(socket.id);room.votes.delete(socket.id);if(!room.players.length){rooms.delete(code);return}if(room.hostId===socket.id)room.hostId=room.players[0].id;if(room.phase==='game'&&room.spyId===socket.id){const deltas={};room.players.filter(p=>p.id!==room.spyId).forEach(p=>award(room,p.id,1,deltas));finishRound(room,{title:'👥 Người thường thắng!',detail:'Spy đã rời phòng.',winnerType:'nonspy',winnerNames:room.players.map(p=>p.name),deltas});return}if(room.phase==='discussion'&&room.votes.size===room.players.length)resolveVote(room);if(room.phase==='game'&&room.turnIndex>=room.players.length)room.turnIndex=0;emitRoom(room)});
});
const PORT=process.env.PORT||10000;server.listen(PORT,'0.0.0.0',()=>console.log(`Spyfall listening on ${PORT}`));