const express=require('express');const http=require('http');const{Server}=require('socket.io');const path=require('path');const app=express(),server=http.createServer(app),io=new Server(server);app.use(express.static(path.join(__dirname)));app.get('/',(_,res)=>res.sendFile(path.join(__dirname,'spy-mission.html')));app.get('/health',(_,res)=>res.json({ok:true,mode:'secret-mission'}));
const locations=['Đại học','Sở thú','Rạp hát','Đồn cảnh sát','Câu lạc bộ đêm','Tàu biển','Tàu cướp biển','Tàu chở khách','Trạm Bắc Cực','Căn cứ quân sự','Hãng phim','Bệnh viện','Đại sứ quán','Khách sạn','Spa','Lều gánh xiếc','Quân Thập Tự','Sòng bạc','Tiệc công ty','Bãi biển','Công viên giải trí','Hội chợ','Ngân hàng','Máy bay','Siêu thị','Tàu ngầm','Trạm vũ trụ','Trạm dịch vụ','Trường học','Nhà hàng'];
const missions=['Hỏi một người về nghề nghiệp của họ.','Hỏi một người xem họ sẽ làm gì nếu có sự cố ở đây.','Nhắc đến một đồ vật có thể xuất hiện ở địa điểm này.','Hỏi một người một câu có thể trả lời Có hoặc Không.','Đặt một câu hỏi mà không dùng từ “ở đây”.','Hỏi một người về thời gian họ thường ở địa điểm này.','Hỏi một người xem họ có muốn quay lại đây không.','Hỏi một người chưa từng bị bạn hỏi.','Trả lời một câu hỏi bằng đúng 5 từ.','Cố tình trả lời một câu hỏi thật mơ hồ.','Hỏi một người về điều họ thích nhất ở địa điểm này.','Hỏi một người về điều họ không thích ở địa điểm này.','Trong lượt của bạn, hãy hỏi một người bất kỳ.','Hỏi một câu liên quan đến công việc tại địa điểm này.','Hỏi một người xem họ thường đi cùng ai.','Hỏi một câu khiến người kia phải giải thích thêm.','Nhắc đến một màu sắc trong câu hỏi hoặc câu trả lời.','Hỏi một người xem nơi này có phù hợp cho trẻ em không.','Hỏi một người về trang phục phù hợp ở đây.','Hỏi một người xem họ sẽ mang gì đến đây.'];
const rooms=new Map(),code=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c},spies=r=>r.players.filter(p=>r.spyIds.includes(p.id));
function state(r,id){return{room:r.code,selfId:id,players:r.players.map(p=>({id:p.id,name:p.name,score:p.score})),hostId:r.hostId,phase:r.phase,round:r.round,turnIndex:r.turnIndex,timer:r.endsAt?Math.max(0,Math.ceil((r.endsAt-Date.now())/1000)):0,location:r.phase==='lobby'||r.players.find(p=>p.id===id)&&!r.spyIds.includes(id)?r.location:null,locations,qa:r.qa,chat:r.chat,votes:Object.fromEntries(r.votes),spyCount:r.spyCount,asked:[...r.asked],pending:r.pending?{fromId:r.pending.fromId,toId:r.pending.toId,q:r.pending.q}:null}}
function emit(r){r.players.forEach(p=>{const s=io.sockets.sockets.get(p.id);if(s){const x=state(r,p.id);s.emit('state',x);s.emit('room_state',x)}})}
function finish(r,title,detail,deltas={}){if(r.phase==='result')return;r.phase='result';clearTimeout(r.timerId);io.to(r.code).emit('result',{title,detail,location:r.location,spyIds:r.spyIds,scores:Object.fromEntries(r.players.map(p=>[p.id,p.score])),deltas});emit(r)}
function start(r){r.phase='game';r.round++;r.location=locations[Math.floor(Math.random()*locations.length)];const pool=[...r.players];r.spyIds=[];for(let i=0;i<r.spyCount;i++)r.spyIds.push(pool.splice(Math.floor(Math.random()*pool.length),1)[0].id);r.players.forEach(p=>{p.mission=missions[Math.floor(Math.random()*missions.length)];p.missionDone=false});r.turnIndex=Math.floor(Math.random()*r.players.length);r.pending=null;r.asked=new Set;r.qa=[];r.chat=[];r.votes=new Map;r.endsAt=Date.now()+600000;clearTimeout(r.timerId);r.timerId=setTimeout(()=>{const d={};spies(r).forEach(p=>{p.score+=2;d[p.id]=2});finish(r,'🕵️ Spy thắng!','Hết 10 phút mà chưa bắt được Spy.',d)},600000);r.players.forEach(p=>io.to(p.id).emit('role',{spy:r.spyIds.includes(p.id),location:r.spyIds.includes(p.id)?null:r.location,mission:p.mission}));emit(r)}
function discussion(r){r.phase='discussion';r.pending=null;r.votes=new Map;r.chat.push({message:'💬 Tất cả người chơi đã được hỏi. Bắt đầu thảo luận và bỏ phiếu!',system:true,time:Date.now()});emit(r)}
function resolve(r){if(r.votes.size<r.players.length)return;const c={};for(const v of r.votes.values())c[v]=(c[v]||0)+1;let target=r.players[0];r.players.forEach(p=>{if((c[p.id]||0)>(c[target.id]||0))target=p});if(r.spyIds.includes(target.id)){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>{p.score++;d[p.id]=1});finish(r,'👥 Người thường thắng!',`${target.name} được nhóm xác định đúng là Spy.`,d)}else{const d={};spies(r).forEach(p=>{p.score+=4;d[p.id]=4});finish(r,'🕵️ Spy thắng!',`${target.name} bị chọn nhưng không phải Spy.`,d)}}
io.on('connection',s=>{
 s.on('create_room',({name,spyCount=1})=>{const p={id:s.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0},r={code:code(),hostId:s.id,players:[p],phase:'lobby',round:0,turnIndex:0,spyCount:Number(spyCount)===2?2:1,spyIds:[],location:null,pending:null,asked:new Set,qa:[],chat:[],votes:new Map,endsAt:0};rooms.set(r.code,r);s.join(r.code);s.roomCode=r.code;s.emit('joined',{room:r.code,selfId:s.id,name:p.name});emit(r)});
 s.on('join_room',({room,code,name})=>{const r=rooms.get(String(room||code||'').trim().toUpperCase());if(!r)return s.emit('error_msg','Không tìm thấy phòng. Kiểm tra lại mã phòng.');if(r.phase!=='lobby')return s.emit('error_msg','Ván đã bắt đầu, không thể vào phòng.');if(r.players.length>=12)return s.emit('error_msg','Phòng đã đủ 12 người.');const p={id:s.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};r.players.push(p);s.join(r.code);s.roomCode=r.code;s.emit('joined',{room:r.code,selfId:s.id,name:p.name});emit(r)});
 s.on('set_spy_count',({count,spyCount})=>{const r=rooms.get(s.roomCode),n=Number(count??spyCount);if(r&&r.phase==='lobby'&&r.hostId===s.id&&(n===1||n===2)){r.spyCount=n;emit(r)}});
 s.on('start',()=>{const r=rooms.get(s.roomCode);if(!r)return;if(r.phase!=='lobby')return;if(r.players.length<3)return s.emit('error_msg',`Cần ít nhất 3 người để bắt đầu. Hiện có ${r.players.length}/3.`);start(r)});
 s.on('ask',({targetId,q})=>{const r=rooms.get(s.roomCode);if(!r||r.phase!=='game'||r.pending||r.players[r.turnIndex]?.id!==s.id)return;const t=r.players.find(p=>p.id===targetId),text=String(q||'').trim().slice(0,180);if(!t||t.id===s.id||r.asked.has(t.id)||!text)return;r.pending={fromId:s.id,toId:t.id,q:text};io.to(t.id).emit('question',{fromId:s.id,fromName:r.players.find(p=>p.id===s.id).name,q:text});emit(r)});
 s.on('answer',({answer})=>{const r=rooms.get(s.roomCode);if(!r||r.phase!=='game'||!r.pending||r.pending.toId!==s.id)return;const f=r.players.find(p=>p.id===r.pending.fromId),t=r.players.find(p=>p.id===s.id),a=String(answer||'').trim().slice(0,180);if(!f||!t||!a)return;r.qa.push({from:f.name,to:t.name,q:r.pending.q,a});r.asked.add(t.id);r.turnIndex=r.players.findIndex(p=>p.id===t.id);r.pending=null;if(r.players.every(p=>r.asked.has(p.id)))return discussion(r);emit(r)});
 s.on('mission_done',()=>{const r=rooms.get(s.roomCode),p=r?.players.find(p=>p.id===s.id);if(!p||r.phase==='result'||p.missionDone)return;p.missionDone=true;p.score+=2;s.emit('mission_ok');emit(r)});
 s.on('chat',({message})=>{const r=rooms.get(s.roomCode),p=r?.players.find(p=>p.id===s.id),text=String(message||'').trim().slice(0,300);if(!r||!['game','discussion'].includes(r.phase)||!p||!text)return;r.chat.push({from:p.name,message:text,time:Date.now()});emit(r)});
 s.on('vote',({targetId})=>{const r=rooms.get(s.roomCode),t=r?.players.find(p=>p.id===targetId);if(!r||r.phase!=='discussion'||!t||t.id===s.id)return;r.votes.set(s.id,t.id);emit(r);resolve(r)});
 s.on('guess',({location})=>{const r=rooms.get(s.roomCode);if(!r||!['game','discussion'].includes(r.phase)||!r.spyIds.includes(s.id))return;const p=r.players.find(x=>x.id===s.id),g=String(location||'').trim();if(g.toLowerCase()===r.location.toLowerCase()){p.score+=4;finish(r,'🕵️ Spy thắng!',`${p.name} đoán đúng địa điểm: ${r.location}.`,{[p.id]:4})}else{const d={};r.players.filter(x=>!r.spyIds.includes(x.id)).forEach(x=>{x.score++;d[x.id]=1});finish(r,'👥 Người thường thắng!',`${p.name} đoán sai. Địa điểm là ${r.location}.`,d)}});
 s.on('next',()=>{const r=rooms.get(s.roomCode);if(r&&r.phase==='result')start(r)});
 s.on('leave',()=>{const r=rooms.get(s.roomCode);if(!r)return;r.players=r.players.filter(p=>p.id!==s.id);if(!r.players.length){rooms.delete(r.code);return}if(r.hostId===s.id)r.hostId=r.players[0].id;emit(r);s.roomCode=null;s.disconnect(true)});
 s.on('disconnect',()=>{const r=rooms.get(s.roomCode);if(!r)return;r.players=r.players.filter(p=>p.id!==s.id);if(!r.players.length){rooms.delete(r.code);return}if(r.hostId===s.id)r.hostId=r.players[0].id;if(r.phase==='game'&&r.spyIds.includes(s.id)){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>{p.score++;d[p.id]=1});finish(r,'👥 Người thường thắng!','Một Spy đã rời phòng.',d)}else emit(r)})
});server.listen(process.env.PORT||10000,'0.0.0.0');