const express=require('express');
const http=require('http');
const{Server}=require('socket.io');
const path=require('path');
const app=express();
const server=http.createServer(app);
const io=new Server(server);
app.use(express.static(path.join(__dirname)));
app.get('/health',(_,res)=>res.json({ok:true}));

const roles={
'Đại học':['Giáo sư','Sinh viên','Giảng viên','Hiệu trưởng','Trợ giảng','Nhân viên thư viện','Bảo vệ','Nhân viên phòng thí nghiệm','Cố vấn học tập','Nhân viên hành chính'],
'Sở thú':['Nhân viên chăm sóc thú','Bác sĩ thú y','Quản lý sở thú','Người cho thú ăn','Nhân viên bán vé','Khách tham quan','Hướng dẫn viên','Nhân viên vệ sinh','Nhân viên khu bò sát','Nhiếp ảnh gia'],
'Rạp hát':['Diễn viên','Đạo diễn','Khán giả','Nhân viên bán vé','Nhân viên sân khấu','Nhân viên âm thanh','Nhân viên ánh sáng','Nhà sản xuất','Hóa trang','Nhân viên hậu đài'],
'Đồn cảnh sát':['Cảnh sát tuần tra','Điều tra viên','Trưởng đồn','Tù nhân','Luật sư','Nhân viên trực ban','Cảnh sát giao thông','Kỹ thuật viên hình sự','Người tố giác','Thư ký'],
'Câu lạc bộ đêm':['DJ','Bartender','Khách','Bảo vệ','Quản lý câu lạc bộ','Nhân viên phục vụ','Vũ công','Nhân viên thu ngân','Nhân viên âm thanh','Nhân viên giữ xe'],
'Tàu biển':['Thuyền trưởng','Thủy thủ','Hành khách','Đầu bếp','Nhân viên phục vụ','Kỹ sư máy tàu','Nhân viên boong tàu','Hoa tiêu','Nhân viên cứu hộ','Nhân viên vệ sinh'],
'Tàu cướp biển':['Thuyền trưởng hải tặc','Cướp biển','Hoa tiêu','Thủy thủ','Người bị bắt','Đầu bếp','Xạ thủ','Người canh gác','Kẻ đào ngũ','Người tìm kho báu'],
'Tàu chở khách':['Thuyền trưởng','Hành khách','Tiếp viên tàu','Thủy thủ','Nhân viên bán vé','Đầu bếp','Kỹ sư máy tàu','Nhân viên an ninh','Nhân viên cứu hộ','Hoa tiêu'],
'Trạm Bắc Cực':['Nhà khoa học','Nhà khí tượng','Bác sĩ','Kỹ sư','Nhân viên hậu cần','Nhân viên liên lạc','Nhà nghiên cứu động vật','Đội trưởng trạm','Kỹ thuật viên','Nhân viên bảo trì'],
'Căn cứ quân sự':['Chỉ huy','Binh sĩ','Sĩ quan','Quân y','Kỹ thuật viên','Nhân viên hậu cần','Lính canh','Phi công quân sự','Nhân viên thông tin','Tân binh'],
'Hãng phim':['Đạo diễn','Diễn viên','Nhà sản xuất','Quay phim','Biên kịch','Chuyên viên hóa trang','Thiết kế phục trang','Kỹ thuật viên âm thanh','Nhân viên ánh sáng','Trợ lý đạo diễn'],
'Bệnh viện':['Bác sĩ','Y tá','Bệnh nhân','Bác sĩ phẫu thuật','Dược sĩ','Lễ tân','Kỹ thuật viên xét nghiệm','Hộ lý','Bảo vệ','Nhân viên cấp cứu'],
'Đại sứ quán':['Đại sứ','Nhà ngoại giao','Nhân viên lãnh sự','Khách đến làm visa','Phiên dịch viên','Nhân viên an ninh','Thư ký','Nhân viên hành chính','Quan chức chính phủ','Nhân viên tiếp tân'],
'Khách sạn':['Lễ tân','Khách thuê phòng','Quản lý khách sạn','Nhân viên buồng phòng','Nhân viên hành lý','Nhân viên nhà hàng','Bảo vệ','Nhân viên đặt phòng','Nhân viên bảo trì','Nhân viên phục vụ'],
'Spa':['Khách hàng','Kỹ thuật viên massage','Chuyên viên chăm sóc da','Quản lý spa','Lễ tân','Nhân viên gội đầu','Chuyên viên trị liệu','Nhân viên vệ sinh','Thu ngân','Tư vấn viên'],
'Lều gánh xiếc':['Nghệ sĩ xiếc','Chú hề','Người nhào lộn','Người huấn luyện thú','Ảo thuật gia','Người bán vé','Khán giả','Người dẫn chương trình','Nhân viên hậu đài','Người bán đồ ăn'],
'Quân Thập Tự':['Hiệp sĩ','Vua','Nữ hoàng','Lính canh','Tu sĩ','Thợ rèn','Nông dân','Sứ giả','Cung thủ','Người chữa bệnh'],
'Sòng bạc':['Người chơi bài','Dealer','Quản lý sòng bạc','Nhân viên an ninh','Người chơi roulette','Nhân viên thu ngân','Người chơi máy slot','Nhân viên phục vụ','Thanh tra','Khách VIP'],
'Tiệc công ty':['Giám đốc','Nhân viên kinh doanh','Nhân viên nhân sự','Kế toán','Khách mời','Quản lý','Nhân viên marketing','Nhân viên phục vụ','Nhiếp ảnh gia','Đối tác'],
'Bãi biển':['Du khách','Nhân viên cứu hộ','Người bán hàng rong','Người lướt sóng','Ngư dân','Nhân viên cho thuê dù','Người bơi','Nhân viên vệ sinh','Nhiếp ảnh gia','Người bán kem'],
'Công viên giải trí':['Khách tham quan','Nhân viên trò chơi','Người bán vé','Nhân viên bảo trì','Nhân viên an ninh','Nhân viên bán đồ ăn','Người điều khiển tàu lượn','Mascot','Nhân viên vệ sinh','Quản lý công viên'],
'Hội chợ':['Khách tham quan','Người bán hàng','Người bán đồ ăn','Người chơi trò chơi','Nhân viên tổ chức','Bảo vệ','Người bán vé','Nghệ sĩ biểu diễn','Người trúng thưởng','Nhân viên vệ sinh'],
'Ngân hàng':['Giao dịch viên','Khách hàng','Bảo vệ','Quản lý chi nhánh','Nhân viên tín dụng','Thu ngân','Nhân viên kho quỹ','Kiểm toán viên','Nhân viên tư vấn','Nhân viên IT'],
'Máy bay':['Cơ trưởng','Cơ phó','Tiếp viên hàng không','Hành khách','Nhân viên mặt đất','Kỹ thuật viên máy bay','Nhân viên an ninh','Phi công tập sự','Nhân viên phục vụ suất ăn','Nhân viên điều phối'],
'Siêu thị':['Thu ngân','Khách hàng','Nhân viên quầy hàng','Quản lý siêu thị','Nhân viên kho','Bảo vệ','Nhân viên thu ngân trưởng','Nhân viên giao hàng','Nhân viên vệ sinh','Nhân viên chăm sóc khách hàng'],
'Tàu ngầm':['Thuyền trưởng','Sĩ quan','Thủy thủ','Kỹ sư máy','Kỹ thuật viên sonar','Nhân viên liên lạc','Bác sĩ quân y','Thủy thủ trưởng','Nhân viên vũ khí','Học viên'],
'Trạm vũ trụ':['Phi hành gia','Chỉ huy trạm','Nhà khoa học','Kỹ sư','Bác sĩ','Chuyên gia robot','Kỹ thuật viên liên lạc','Nhà sinh học','Nhân viên điều khiển mặt đất','Phi hành gia tập sự'],
'Trạm dịch vụ':['Nhân viên bán xăng','Khách đổ xăng','Thợ sửa xe','Thu ngân','Quản lý trạm','Nhân viên rửa xe','Tài xế xe tải','Nhân viên cửa hàng tiện lợi','Nhân viên bảo trì','Nhân viên vệ sinh'],
'Trường học':['Giáo viên','Học sinh','Hiệu trưởng','Giám thị','Nhân viên y tế','Bảo vệ','Nhân viên thư viện','Cô lao công','Phụ huynh','Nhân viên văn phòng'],
'Nhà hàng':['Đầu bếp','Phụ bếp','Phục vụ bàn','Khách hàng','Quản lý nhà hàng','Thu ngân','Nhân viên pha chế','Nhân viên tiếp tân','Nhân viên giao hàng','Nhân viên vệ sinh']};
const locations=Object.keys(roles);const rooms=new Map();const makeCode=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};const spiesOf=r=>r.players.filter(p=>r.spyIds.includes(p.id));const scoreValue=(r,n)=>r.extraRound?(n>=2?Math.floor(n/2):0):n;
const publicState=r=>({room:r.code,players:r.players.map(p=>({id:p.id,name:p.name,score:p.score})),hostId:r.hostId,phase:r.phase,round:r.round,turnIndex:r.turnIndex,timer:Math.max(0,Math.ceil((r.endsAt-Date.now())/1000)),qa:r.qa,scores:Object.fromEntries(r.players.map(p=>[p.id,p.score])),locations,askedIds:[...r.askedIds],lastQuestionerId:r.lastQuestionerId,chat:r.chat||[],votes:r.phase==='discussion'?Object.fromEntries(r.votes||[]):{},pending:r.pending?{fromId:r.pending.fromId,toId:r.pending.toId,q:r.pending.q}:null,spyCount:r.spyCount,matchOver:!!r.matchOver,matchWinners:r.matchWinners||[],extraRound:!!r.extraRound,turnPreview:r.turnPreview?{fromId:r.turnPreview.fromId,toId:r.turnPreview.toId}:null});
const emitRoom=r=>io.to(r.code).emit('room_state',publicState(r));const emitRole=(r,p)=>io.to(p.id).emit('role',{spy:r.spyIds.includes(p.id),location:r.spyIds.includes(p.id)?null:r.location,role:r.spyIds.includes(p.id)?null:p.role,spyCount:r.spyCount});
function addChat(r,from,message){r.chat.push({from,message,time:Date.now(),system:!from});if(r.chat.length>100)r.chat.shift()}function award(r,id,n,d){const points=scoreValue(r,n);const p=r.players.find(x=>x.id===id);if(p&&points){p.score+=points;d[id]=(d[id]||0)+points}}
function finishRound(r,o){if(r.phase==='result')return;r.phase='result';if(r.timerId)clearTimeout(r.timerId);if(r.noticeTimer)clearTimeout(r.noticeTimer);const winners=r.players.filter(p=>p.score>=5);if(winners.length&&!r.matchOver){r.matchOver=true;r.matchWinners=winners.map(p=>p.id);o.detail+=` ${winners.map(p=>p.name).join(', ')} đã đạt 5 điểm và thắng toàn bộ game!`}const scores=Object.fromEntries(r.players.map(p=>[p.id,p.score]));const deltaNames=Object.fromEntries(r.players.map(p=>[p.id,o.deltas?.[p.id]||0]));io.to(r.code).emit('round_result',{title:o.title,detail:o.detail,location:r.location,spyIds:r.spyIds,scores,winnerType:o.winnerType,winnerNames:o.winnerNames||[],roundDeltas:deltaNames,matchOver:r.matchOver,matchWinners:r.matchWinners||[],extraRound:!!r.extraRound});emitRoom(r)}
function endSpyCaught(r,initiator,target){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));award(r,initiator.id,1,d);finishRound(r,{title:'👥 Người thường thắng!',detail:`${initiator.name} tố cáo ${target.name} và xác định đúng Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}
function accuse(r,voterId,targetId){if(!r||!['game','discussion'].includes(r.phase))return;const voter=r.players.find(p=>p.id===voterId),target=r.players.find(p=>p.id===targetId);if(!voter||!target||target.id===voter.id)return;addChat(r,'',`🚨 ${voter.name} tố cáo ${target.name} là Gián điệp!`);if(r.spyIds.includes(target.id))return endSpyCaught(r,voter,target);const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${voter.name} tố cáo ${target.name}, nhưng đó không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}
function spyGuess(r,spyId,guess){if(!r||!['game','discussion'].includes(r.phase)||!r.spyIds.includes(spyId))return;const spy=r.players.find(p=>p.id===spyId),g=String(guess||'').trim();if(!spy||!g)return;addChat(r,'',`🎯 ${spy.name} đã đoán địa điểm: ${g}`);if(g.toLowerCase()===r.location.toLowerCase()){const d={};award(r,spy.id,4,d);return finishRound(r,{title:'🕵️ Spy thắng!',detail:`${spy.name} đoán đúng địa điểm: ${r.location}.`,winnerType:'spy',winnerNames:[spy.name],deltas:d})}const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${spy.name} đoán sai. Địa điểm là ${r.location}.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}
function resolveVote(r){if(r.phase!=='discussion')return;const counts={};for(const id of r.votes.values())counts[id]=(counts[id]||0)+1;let max=0,chosen=[];for(const p of r.players){const n=counts[p.id]||0;if(n>max){max=n;chosen=[p.id]}else if(n===max&&n>0)chosen.push(p.id)}if(!chosen.length)return;const target=r.players.find(p=>p.id===chosen[0]);if(!target)return;if(r.spyIds.includes(target.id)){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:`${target.name} được chọn nhiều nhất và bị xác định là Gián điệp.`,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}else{const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail:`${target.name} được chọn nhiều nhất nhưng không phải Gián điệp.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}}
function enterDiscussion(r){if(r.phase!=='game')return;r.phase='discussion';r.pending=null;r.turnPreview=null;r.votes=new Map();addChat(r,'','💬 Tất cả người chơi đã hỏi xong. Bắt đầu thảo luận và bỏ phiếu tìm Gián điệp!');io.to(r.code).emit('discussion_start');emitRoom(r)}
function enterDecision(r){if(r.phase!=='game')return;r.phase='round_decision';r.pending=null;r.turnPreview=null;r.votes=new Map();addChat(r,'','⚠️ Đã kết thúc vòng hỏi. Hãy thảo luận xem có thêm 1 vòng hay không. Nếu thêm vòng, điểm của kết quả cuối sẽ giảm 1/2.');io.to(r.code).emit('round_decision_start',{round:r.round,playerCount:r.players.length,extraRound:!!r.extraRound});emitRoom(r)}
function resolveRoundDecision(r){if(r.phase!=='round_decision')return;let yes=0,no=0;for(const v of r.votes.values()){if(v==='yes')yes++;else no++}if(yes>=no){addChat(r,'','🔄 Đa số chọn THÊM VÒNG. Bắt đầu VÒNG 2.');startQuestionRound(r,true)}else{addChat(r,'','⛔ Đa số chọn KHÔNG THÊM VÒNG. Chuyển sang thảo luận.');enterDiscussion(r)}}
function startQuestionRound(r,extra){r.phase='game';r.round=extra?2:1;r.extraRound=!!extra;r.askedIds=new Set();r.lastQuestionerId=null;r.pending=null;r.turnPreview=null;r.votes=new Map();r.qa=extra?r.qa:[];r.turnIndex=Math.floor(Math.random()*r.players.length);const seconds=r.players.length*(extra?60:120);r.endsAt=Date.now()+seconds*1000;if(r.timerId)clearTimeout(r.timerId);if(r.noticeTimer)clearTimeout(r.noticeTimer);r.noticeTimer=setTimeout(()=>{if(r.phase==='game'){addChat(r,'','⏰ Còn 1 phút! Hãy nhanh chóng tìm Gián điệp hoặc để Spy đoán địa điểm.');emitRoom(r)}},Math.max(1000,(seconds-60)*1000));r.timerId=setTimeout(()=>{const d={};spiesOf(r).forEach(p=>award(r,p.id,2,d));addChat(r,'','⏰ Hết thời gian! Chưa có ai bắt được Spy.');finishRound(r,{title:'🕵️ Spy thắng!',detail:`Hết thời gian mà chưa có ai bắt được Spy. Mỗi Spy nhận ${r.extraRound?1:2} điểm.`,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})},seconds*1000);emitRoom(r);for(const p of r.players)emitRole(r,p)}
function startRound(r){if(r.players.length<3)return;r.round=0;r.location=locations[Math.floor(Math.random()*locations.length)];r.spyIds=[];const pool=[...r.players];for(let i=0;i<r.spyCount;i++){const j=Math.floor(Math.random()*pool.length);r.spyIds.push(pool.splice(j,1)[0].id)}const rolePool=[...roles[r.location]];for(let i=rolePool.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[rolePool[i],rolePool[j]]=[rolePool[j],rolePool[i]]}r.players.filter(p=>!r.spyIds.includes(p.id)).forEach((p,i)=>p.role=rolePool[i]);r.qa=[];r.chat=[];r.matchOver=false;r.matchWinners=[];startQuestionRound(r,false)}
function removePlayer(r,id){r.players=r.players.filter(p=>p.id!==id);r.askedIds.delete(id);r.votes.delete(id);if(r.hostId===id&&r.players.length)r.hostId=r.players[0].id}

io.on('connection',socket=>{
socket.on('create_room',({name,spyCount=1})=>{const code=makeCode();const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0,role:null};const sc=Number(spyCount)===2?2:1;const r={code,hostId:p.id,players:[p],phase:'lobby',round:0,turnIndex:0,qa:[],pending:null,askedIds:new Set(),lastQuestionerId:null,chat:[],votes:new Map(),spyCount:sc,spyIds:[],location:null,matchOver:false,matchWinners:[],extraRound:false,turnPreview:null};rooms.set(code,r);socket.join(code);socket.roomCode=code;socket.playerId=socket.id;socket.emit('joined',{room:code,selfId:socket.id});emitRoom(r)});
socket.on('join_room',({code,name})=>{const r=rooms.get(String(code||'').toUpperCase());if(!r)return socket.emit('error_msg','Không tìm thấy phòng.');if(!['lobby','result'].includes(r.phase)||r.matchOver)return socket.emit('error_msg','Ván đang diễn ra hoặc game đã kết thúc.');if(r.players.length>=12)return socket.emit('error_msg','Phòng đã đủ 12 người.');const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0,role:null};r.players.push(p);socket.join(r.code);socket.roomCode=r.code;socket.playerId=socket.id;socket.emit('joined',{room:r.code,selfId:socket.id});emitRoom(r)});
socket.on('set_spy_count',({spyCount})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(spyCount);if(n===1||n===2){r.spyCount=n;emitRoom(r)}});
socket.on('kick_player',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id||targetId===socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t)return;io.to(t.id).emit('kicked','Bạn đã bị Host đuổi khỏi phòng.');const s=io.sockets.sockets.get(t.id);if(s){s.roomCode=null;s.disconnect(true)}removePlayer(r,targetId);emitRoom(r)});
socket.on('leave_room',()=>{const r=rooms.get(socket.roomCode);if(!r)return;const id=socket.playerId||socket.id;const wasSpy=r.spyIds.includes(id);removePlayer(r,id);socket.leave(r.code);socket.roomCode=null;if(!r.players.length){rooms.delete(r.code);return}if(['game','round_decision'].includes(r.phase)&&wasSpy){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:'Một Gián điệp đã rời phòng.',winnerType:'nonspy',winnerNames:r.players.map(p=>p.name),deltas:d});return}emitRoom(r)});
socket.on('start_game',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.players.length<3||r.phase!=='lobby')return;startRound(r)});
socket.on('request_role',()=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion','round_decision'].includes(r.phase))return;const p=r.players.find(x=>x.id===socket.id);if(p)emitRole(r,p)});
socket.on('select_target',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||r.pending||r.players[r.turnIndex]?.id!==socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t||t.id===socket.id)return;if(r.askedIds.has(t.id))return socket.emit('error_msg','Người này đã được hỏi trong vòng hiện tại.');if(r.lastQuestionerId===t.id)return socket.emit('error_msg','Không được hỏi lại người vừa hỏi mình.');r.turnPreview={fromId:socket.id,toId:t.id};emitRoom(r)});socket.on('send_question',({targetId,question})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||r.pending||r.players[r.turnIndex]?.id!==socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t||t.id===socket.id)return;if(r.askedIds.has(t.id))return socket.emit('error_msg','Người này đã được hỏi trong vòng hiện tại.');if(r.lastQuestionerId===t.id)return socket.emit('error_msg','Không được hỏi lại người vừa hỏi mình.');const q=String(question||'').trim().slice(0,180);if(!q)return;r.turnPreview=null;r.pending={fromId:socket.id,toId:t.id,q};const from=r.players.find(p=>p.id===socket.id);addChat(r,'',`❓ ${from?.name||'Người chơi'} → ${t.name}: ${q}`);io.to(t.id).emit('question_received',{fromId:socket.id,fromName:from?.name||'Người chơi',toId:t.id,q});emitRoom(r)});
socket.on('answer_question',({answer})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||!r.pending||r.pending.toId!==socket.id)return;const from=r.players.find(p=>p.id===r.pending.fromId),to=r.players.find(p=>p.id===socket.id);const a=String(answer||'').trim().slice(0,180);if(!from||!to||!a)return;r.qa.push({from:from.name,to:to.name,q:r.pending.q,a});r.askedIds.add(to.id);r.lastQuestionerId=from.id;r.pending=null;r.turnPreview=null;r.turnIndex=r.players.findIndex(p=>p.id===to.id);if(r.players.every(p=>r.askedIds.has(p.id)))return r.extraRound?enterDiscussion(r):enterDecision(r);emitRoom(r)});
socket.on('chat_message',({message})=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion','round_decision'].includes(r.phase))return;const p=r.players.find(x=>x.id===(socket.playerId||socket.id));const text=String(message||'').trim().slice(0,300);if(!p||!text)return;addChat(r,p.name,text);emitRoom(r)});
socket.on('accuse_vote',({targetId})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='discussion')return;const voterId=socket.playerId||socket.id;if(!r.players.some(p=>p.id===voterId))return;const t=r.players.find(p=>p.id===targetId);if(!t||t.id===voterId)return;r.votes.set(voterId,t.id);addChat(r,'',`🗳️ ${r.players.find(p=>p.id===voterId)?.name||'Người chơi'} đã bỏ phiếu.`);emitRoom(r);if(r.votes.size===r.players.length)resolveVote(r)});
socket.on('round_continue_vote',({continueRound})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='round_decision')return;const voterId=socket.playerId||socket.id;if(!r.players.some(p=>p.id===voterId))return;const v=!!continueRound;r.votes.set(voterId,v?'yes':'no');socket.emit('round_vote_ack',{continueRound:v});if(r.votes.size===r.players.length)resolveRoundDecision(r);else emitRoom(r)});
socket.on('accuse',({targetId})=>{const r=rooms.get(socket.roomCode);accuse(r,socket.playerId||socket.id,targetId)});
socket.on('spy_guess_location',({location})=>{const r=rooms.get(socket.roomCode);spyGuess(r,socket.playerId||socket.id,location)});
socket.on('next_round',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.phase!=='result'||r.matchOver)return;startRound(r)});
socket.on('disconnect',()=>{const r=rooms.get(socket.roomCode);if(!r||socket.playerId!==socket.id)return;const id=socket.id,wasSpy=r.spyIds.includes(id);removePlayer(r,id);if(!r.players.length){rooms.delete(r.code);return}if(['game','round_decision'].includes(r.phase)&&wasSpy){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail:'Một Gián điệp đã rời phòng.',winnerType:'nonspy',winnerNames:r.players.map(p=>p.name),deltas:d});return}emitRoom(r)})});

const PORT=process.env.PORT||10000;server.listen(PORT,'0.0.0.0',()=>console.log('Spyfall server listening on '+PORT));