const express=require('express');
const http=require('http');
const {Server}=require('socket.io');
const path=require('path');
const app=express();
const server=http.createServer(app);
const io=new Server(server);
app.use(express.static(path.join(__dirname)));
app.get('/health',(_,res)=>res.json({ok:true}));
const locations=['Đại học','Sở thú','Rạp hát','Đồn cảnh sát','Câu lạc bộ đêm','Tàu biển','Tàu cướp biển','Tàu chở khách','Trạm Bắc Cực','Căn cứ quân sự','Hãng phim','Bệnh viện','Đại sứ quán','Khách sạn','Spa','Lều gánh xiếc','Quân Thập Tự','Sòng bạc','Tiệc công ty','Bãi biển','Công viên giải trí','Hội chợ','Ngân hàng','Máy bay','Siêu thị','Tàu ngầm','Trạm vũ trụ','Trạm dịch vụ','Trường học','Nhà hàng'];
const rooms=new Map();
const makeCode=()=>{let c;do c=Math.random().toString(36).slice(2,8).toUpperCase();while(rooms.has(c));return c};
const activePhase=p=>['game','discussion','vote1','defense','vote2'].includes(p);
const spiesOf=r=>r.players.filter(p=>r.spyIds.includes(p.id));
const publicState=r=>({room:r.code,players:r.players.map(p=>({id:p.id,name:p.name,score:p.score})),hostId:r.hostId,phase:r.phase,round:r.round,turnIndex:r.turnIndex,timer:Math.max(0,Math.ceil((r.endsAt-Date.now())/1000)),qa:r.qa,scores:Object.fromEntries(r.players.map(p=>[p.id,p.score])),locations,askedIds:[...r.askedIds],lastQuestionerId:r.lastQuestionerId,chat:r.chat||[],votes:Object.fromEntries(r.votes||[]),spyCount:r.spyCount,winScore:r.winScore,matchOver:!!r.matchOver,matchWinners:r.matchWinners||[],voteCandidates:r.voteCandidates||[],defenseEndsAt:r.defenseEndsAt||0,voteStage:r.voteStage||null,voteEligible:r.vote2Eligible||[],vote2:Object.fromEntries(r.vote2||[]),pending:r.pending?{fromId:r.pending.fromId,toId:r.pending.toId,q:r.pending.q}:null});
const emitRoom=r=>io.to(r.code).emit('room_state',publicState(r));
function addChat(r,from,message){r.chat.push({from,message,time:Date.now(),system:!from});if(r.chat.length>100)r.chat.shift()}
function award(r,id,n,d){const p=r.players.find(x=>x.id===id);if(p&&n){p.score+=n;d[id]=(d[id]||0)+n}}
function clearTimers(r){if(r.timerId)clearTimeout(r.timerId);if(r.noticeTimer)clearTimeout(r.noticeTimer);if(r.defenseTimer)clearTimeout(r.defenseTimer);r.timerId=r.noticeTimer=r.defenseTimer=null}
function finishRound(r,o){if(r.phase==='result')return;clearTimers(r);r.phase='result';const winners=r.players.filter(p=>p.score>=r.winScore);if(winners.length&&!r.matchOver){r.matchOver=true;r.matchWinners=winners.map(p=>p.id);o.detail+=` ${winners.map(p=>p.name).join(', ')} đã đạt ${r.winScore} điểm và thắng toàn bộ game!`}const scores=Object.fromEntries(r.players.map(p=>[p.id,p.score]));const roundDeltas=Object.fromEntries(r.players.map(p=>[p.id,o.deltas?.[p.id]||0]));io.to(r.code).emit('round_result',{title:o.title,detail:o.detail,location:r.location,spyIds:r.spyIds,scores,winnerType:o.winnerType,winnerNames:o.winnerNames||[],roundDeltas,matchOver:r.matchOver,matchWinners:r.matchWinners||[],winScore:r.winScore});emitRoom(r)}
function nonSpyWin(r,detail){const d={};r.players.filter(p=>!r.spyIds.includes(p.id)).forEach(p=>award(r,p.id,1,d));finishRound(r,{title:'👥 Người thường thắng!',detail,winnerType:'nonspy',winnerNames:r.players.filter(p=>!r.spyIds.includes(p.id)).map(p=>p.name),deltas:d})}
function spyWin(r,detail){const d={};spiesOf(r).forEach(p=>award(r,p.id,4,d));finishRound(r,{title:'🕵️ Spy thắng!',detail,winnerType:'spy',winnerNames:spiesOf(r).map(p=>p.name),deltas:d})}
function startRound(r){if(r.players.length<3)return;clearTimers(r);r.phase='game';r.round++;r.location=locations[Math.floor(Math.random()*locations.length)];r.spyIds=[];const pool=[...r.players];for(let i=0;i<r.spyCount;i++){const j=Math.floor(Math.random()*pool.length);r.spyIds.push(pool.splice(j,1)[0].id)}r.turnIndex=Math.floor(Math.random()*r.players.length);r.qa=[];r.chat=[];r.votes=new Map();r.vote2=new Map();r.voteCandidates=[];r.voteStage=null;r.vote2Eligible=[];r.defenseEndsAt=0;r.pending=null;r.askedIds=new Set();r.lastQuestionerId=null;r.endsAt=Date.now()+600000;r.noticeTimer=setTimeout(()=>{if(activePhase(r.phase)){addChat(r,'','⏰ Còn 2 phút!');emitRoom(r)}},480000);r.timerId=setTimeout(()=>{if(activePhase(r.phase))spyWin(r,'⏰ Hết thời gian mà chưa có ai bắt được Spy. Mỗi Spy nhận 4 điểm.')},600000);for(const p of r.players)io.to(p.id).emit('role',{spy:r.spyIds.includes(p.id),location:r.spyIds.includes(p.id)?null:r.location,spyCount:r.spyCount});emitRoom(r)}
function enterDiscussion(r){if(r.phase!=='game')return;r.phase='discussion';r.pending=null;addChat(r,'','💬 Tất cả người chơi đã hỏi và trả lời xong. Bắt đầu tố cáo chung!');startVote1(r)}
function startVote1(r){r.phase='vote1';r.voteStage='vote1';r.votes=new Map();r.voteCandidates=[];r.vote2=new Map();r.vote2Eligible=[];r.defenseEndsAt=0;addChat(r,'','🗳️ TỐ CÁO CHUNG: Mọi người cùng bỏ phiếu. Người hoặc nhiều người có cùng số phiếu cao nhất sẽ được 2 phút biện minh.');emitRoom(r)}
function allVoted(map,r){return r.players.every(p=>map.has(p.id))}
function beginDefense(r){if(r.phase!=='vote1')return;const counts={};for(const id of r.votes.values())counts[id]=(counts[id]||0)+1;const max=Math.max(0,...Object.values(counts));if(!max)return startVote2(r,[]);r.voteCandidates=Object.entries(counts).filter(([,n])=>n===max).map(([id])=>id);r.phase='defense';r.voteStage='defense';r.defenseEndsAt=Date.now()+120000;r.endsAt+=240000;addChat(r,'',`⚖️ ${r.voteCandidates.map(id=>r.players.find(p=>p.id===id)?.name).filter(Boolean).join(', ')} cùng có ${max} phiếu cao nhất. Có 2 phút để biện minh. Tổng thời gian ván được cộng thêm 2 phút.`);emitRoom(r);r.defenseTimer=setTimeout(()=>startVote2(r,r.voteCandidates),120000)}
function startVote2(r,candidates){r.phase='vote2';r.voteStage='vote2';r.voteCandidates=candidates||r.voteCandidates||[];r.vote2=new Map();r.vote2Eligible=r.players.filter(p=>!r.voteCandidates.includes(p.id)).map(p=>p.id);addChat(r,'','🗳️ VOTE PHỤ: Những người đang bị tình nghi không được bỏ phiếu. Mọi người còn lại bỏ phiếu lại; ai có nhiều phiếu nhất sẽ bị tố cáo.');emitRoom(r);if(!r.vote2Eligible.length)return resolveVote2(r)}
function resolveVote2(r){if(r.phase!=='vote2')return;const counts={};for(const id of r.vote2.values())counts[id]=(counts[id]||0)+1;const entries=Object.entries(counts);if(!entries.length)return nonSpyWin(r,'Không có phiếu ở lượt Vote phụ.');const max=Math.max(...entries.map(([,n])=>n));const top=entries.filter(([,n])=>n===max).map(([id])=>id);const targetId=top[Math.floor(Math.random()*top.length)];const target=r.players.find(p=>p.id===targetId);if(!target)return;if(r.spyIds.includes(target.id))nonSpyWin(r,`${target.name} bị tố cáo đúng là Gián điệp.`);else spyWin(r,`${target.name} bị tố cáo nhưng không phải Gián điệp.`)}
function accuseDirect(r,voterId,targetId){if(!r||!['game','discussion'].includes(r.phase))return;const voter=r.players.find(p=>p.id===voterId),target=r.players.find(p=>p.id===targetId);if(!voter||!target||voter.id===target.id||r.spyIds.includes(voter.id))return;if(r.spyIds.includes(target.id))nonSpyWin(r,`${voter.name} tố cáo đúng ${target.name} là Gián điệp.`);else spyWin(r,`${voter.name} tố cáo ${target.name}, nhưng người này không phải Gián điệp.`)}
function spyGuess(r,spyId,guess){if(!r||!activePhase(r.phase)||!r.spyIds.includes(spyId))return;const spy=r.players.find(p=>p.id===spyId),g=String(guess||'').trim();if(!spy||!g)return;if(g.toLowerCase()===r.location.toLowerCase())spyWin(r,`${spy.name} đoán đúng địa điểm: ${r.location}.`);else nonSpyWin(r,`${spy.name} đoán sai. Địa điểm là ${r.location}.`)}
function resetToLobby(r){clearTimers(r);r.phase='lobby';r.round=0;r.turnIndex=0;r.qa=[];r.pending=null;r.askedIds=new Set();r.lastQuestionerId=null;r.chat=[];r.votes=new Map();r.vote2=new Map();r.voteCandidates=[];r.voteStage=null;r.defenseEndsAt=0;r.vote2Eligible=[];r.location=null;r.spyIds=[];r.matchOver=false;r.matchWinners=[];r.endsAt=0;r.players.forEach(p=>p.score=0);for(const p of r.players)io.to(p.id).emit('role',{spy:false,location:null,spyCount:r.spyCount});emitRoom(r)}
function removePlayer(r,id){r.players=r.players.filter(p=>p.id!==id);r.askedIds.delete(id);r.votes.delete(id);r.vote2.delete(id);r.vote2Eligible=r.vote2Eligible.filter(x=>x!==id);r.voteCandidates=r.voteCandidates.filter(x=>x!==id);if(r.hostId===id&&r.players.length)r.hostId=r.players[0].id}
io.on('connection',socket=>{
socket.on('create_room',({name,spyCount=1,winScore=5}={})=>{const code=makeCode();const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};const r={code,hostId:p.id,players:[p],phase:'lobby',round:0,turnIndex:0,qa:[],pending:null,askedIds:new Set(),lastQuestionerId:null,chat:[],votes:new Map(),vote2:new Map(),voteCandidates:[],voteStage:null,vote2Eligible:[],defenseEndsAt:0,spyCount:Number(spyCount)===2?2:1,winScore:[5,7,10].includes(Number(winScore))?Number(winScore):5,spyIds:[],location:null,matchOver:false,matchWinners:[]};rooms.set(code,r);socket.join(code);socket.roomCode=code;socket.playerId=socket.id;socket.emit('joined',{room:code,selfId:socket.id});emitRoom(r)});
socket.on('join_room',({code,name}={})=>{const r=rooms.get(String(code||'').toUpperCase());if(!r)return socket.emit('error_msg','Không tìm thấy phòng.');if(r.phase!=='lobby'||r.matchOver)return socket.emit('error_msg','Phòng không ở trạng thái chờ.');if(r.players.length>=12)return socket.emit('error_msg','Phòng đã đủ 12 người.');const p={id:socket.id,name:String(name||'Người chơi').trim().slice(0,20)||'Người chơi',score:0};r.players.push(p);socket.join(r.code);socket.roomCode=r.code;socket.playerId=socket.id;socket.emit('joined',{room:r.code,selfId:socket.id});emitRoom(r)});
socket.on('set_spy_count',({spyCount}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(spyCount);if(n===1||n===2){r.spyCount=n;emitRoom(r)}});
socket.on('set_win_score',({winScore}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id)return;const n=Number(winScore);if([5,7,10].includes(n)){r.winScore=n;emitRoom(r)}});
socket.on('kick_player',({targetId}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='lobby'||r.hostId!==socket.id||targetId===socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t)return;io.to(t.id).emit('kicked','Bạn đã bị Host đuổi khỏi phòng.');const s=io.sockets.sockets.get(t.id);if(s){s.roomCode=null;s.disconnect(true)}removePlayer(r,targetId);emitRoom(r)});
socket.on('start_game',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.players.length<3||r.phase!=='lobby')return;startRound(r)});
socket.on('send_question',({targetId,question}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||r.pending||r.players[r.turnIndex]?.id!==socket.id)return;const t=r.players.find(p=>p.id===targetId);if(!t||t.id===socket.id)return;if(r.askedIds.has(t.id))return socket.emit('error_msg','Người này đã được hỏi trong vòng hiện tại.');if(r.lastQuestionerId===t.id)return socket.emit('error_msg','Không được hỏi lại người vừa hỏi mình.');const q=String(question||'').trim().slice(0,180);if(!q)return;r.pending={fromId:socket.id,toId:t.id,q};io.to(t.id).emit('question_received',{fromId:socket.id,fromName:r.players.find(p=>p.id===socket.id)?.name||'',toId:t.id,q});emitRoom(r)});
socket.on('answer_question',({answer}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='game'||!r.pending||r.pending.toId!==socket.id)return;const from=r.players.find(p=>p.id===r.pending.fromId),to=r.players.find(p=>p.id===socket.id);const a=String(answer||'').trim().slice(0,180);if(!from||!to||!a)return;r.qa.push({from:from.name,to:to.name,q:r.pending.q,a});r.askedIds.add(to.id);r.lastQuestionerId=from.id;r.pending=null;r.turnIndex=r.players.findIndex(p=>p.id===to.id);if(r.players.every(p=>r.askedIds.has(p.id)))return enterDiscussion(r);emitRoom(r)});
socket.on('chat_message',({message}={})=>{const r=rooms.get(socket.roomCode);if(!r||!['game','discussion','vote1','defense','vote2'].includes(r.phase))return;const p=r.players.find(x=>x.id===(socket.playerId||socket.id));const text=String(message||'').trim().slice(0,300);if(!p||!text)return;addChat(r,p.name,text);emitRoom(r)});
socket.on('chat_defense',({message}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='defense')return;const p=r.players.find(x=>x.id===(socket.playerId||socket.id));const text=String(message||'').trim().slice(0,300);if(!p||!text)return;addChat(r,p.name,`⚖️ Biện minh: ${text}`);emitRoom(r)});
socket.on('accuse_vote',({targetId}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='vote1')return;const id=socket.playerId||socket.id;if(!r.players.some(p=>p.id===id))return;if(!targetId){r.votes.delete(id);emitRoom(r);return}const t=r.players.find(p=>p.id===targetId);if(!t||t.id===id)return;r.votes.set(id,t.id);emitRoom(r);if(allVoted(r.votes,r))beginDefense(r)});
socket.on('accuse_vote2',({targetId}={})=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='vote2')return;const id=socket.playerId||socket.id;if(!r.vote2Eligible.includes(id))return;if(!targetId){r.vote2.delete(id);emitRoom(r);return}const t=r.players.find(p=>p.id===targetId);if(!t||t.id===id)return;r.vote2.set(id,t.id);emitRoom(r);if(r.vote2Eligible.every(x=>r.vote2.has(x)))resolveVote2(r)});
socket.on('accuse',({targetId}={})=>accuseDirect(rooms.get(socket.roomCode),socket.playerId||socket.id,targetId));
socket.on('spy_guess_location',({location}={})=>spyGuess(rooms.get(socket.roomCode),socket.playerId||socket.id,location));
socket.on('next_round',()=>{const r=rooms.get(socket.roomCode);if(!r||r.hostId!==socket.id||r.phase!=='result'||r.matchOver)return;startRound(r)});
socket.on('return_to_lobby',()=>{const r=rooms.get(socket.roomCode);if(!r||r.phase!=='result')return;resetToLobby(r)});
socket.on('leave_room',()=>{const r=rooms.get(socket.roomCode);if(!r)return;const id=socket.playerId||socket.id;const wasSpy=r.spyIds.includes(id);removePlayer(r,id);socket.leave(r.code);socket.roomCode=null;if(!r.players.length){rooms.delete(r.code);return}if(activePhase(r.phase)&&wasSpy){nonSpyWin(r,'Một Gián điệp đã rời phòng.');return}emitRoom(r)});
socket.on('disconnect',()=>{const r=rooms.get(socket.roomCode);if(!r)return;const id=socket.playerId||socket.id;const wasSpy=r.spyIds.includes(id);removePlayer(r,id);if(!r.players.length){rooms.delete(r.code);return}if(activePhase(r.phase)&&wasSpy){nonSpyWin(r,'Một Gián điệp đã mất kết nối.');return}emitRoom(r)});
});
const PORT=process.env.PORT||10000;server.listen(PORT,'0.0.0.0',()=>console.log(`Spyfall Online listening on ${PORT}`));